const fs=require('fs'),vm=require('vm');
let html=fs.readFileSync('ui-base.html','utf8');
let css=html.match(/<style>([\s\S]*?)<\/style>/)[1],js=html.match(/<script>([\s\S]*)<\/script>/)[1];
js=js.replace(/const initial=\[[\s\S]*?\];\n/,'').replace('products=initial.map(p=>({...p}))','products=[]');
js=js.replace(/const orderReferenceImage='[^']*';\n/,'');
const remove=['review','newForm','saveProduct','showImport','validateImport','importCommit','showUpdate','runUpdate','backup','exportOrder','setPhotoSample','beginPhotoDemo','photoPage'];
for(const name of remove)js=js.replace(new RegExp('^(?:async )?function '+name+'\\([^\\n]*\\n','m'),'');
const start=js.indexOf('// Minimal standards-compliant XLSX export:');const end=js.indexOf("document.addEventListener('click'",start);js=js.slice(0,start)+js.slice(end);
js=js.replace(/^function art\([^\n]*$/m,`function art(p){return p.image?'<img class="real-product-image" src="/api/images/'+esc(p.image)+'" alt="'+esc(p.name)+'">':'<div class="no-product-image">'+icon('image')+'<small>暂无图片</small></div>'}`);
js=js.replace(/\+p\.code\+/g,'+esc(p.code)+').replace(/\+p\.factoryCode\+/g,'+esc(p.factoryCode)+');
js=js.replace(/\+p\.cat\+/g,'+esc(p.cat)+');
js=js.replace("p.color+'", "(p.color||'#f3f6fa')+'");
js=js.replaceAll("+p.color+","+(p.color||'#f3f6fa')+");
js=js.replace("photoUrl=next;photoName=file.name;","photoFile=file;photoUrl=next;photoName=file.name;");
js=js.replace('演示识别文本','识别原文');
js=js.replace('演示模式：以下是固定示例行，不是这张照片的真实识别结果。可以修改商品、数量和单位体验确认流程。','离线识别结果需要人工核对，可能漏行或错字。请对照原图检查并补充，不能直接作为下单依据。');
js=js.replace("'</div><div class=\"ocr-layout\">'","'</div><div class=\"ocr-layout\">'");
js=js.replace('<div class="ocr-layout"><aside', '<details class="raw-ocr"><summary>查看全部识别原文</summary><pre>\'+esc(ocrLines.map(l=>l.text).join(\'\\n\')||\'无识别原文，可手动录入\')+\'</pre></details><div class="ocr-layout"><aside');
js=js.replaceAll('共 '+"'+rows.length+'"+' 款商品 · 示意图片','共 '+"'+rows.length+'"+' 款商品');
js=js.replaceAll(' · 示意图片','');
js=js.replaceAll('商品示意图','商品图片');
js=js.replace('下载为示例报货单，不会自动发送给厂家。','下载生成的报货单，不会自动发送给厂家。');
js=js.replace('当前原型刷新后清空，正式版可保存未完成清单。','未完成清单会保存在本机，关闭重开后可继续。');
js=js.replace("function render(){document.body", "function render(){if(!appReady)return;document.body");
js=js.replace("all.indeterminate=count>0&&count<rows.length}}", "all.indeterminate=count>0&&count<rows.length}persistDraft()}");
js=js.replace(/;render\(\);\s*$/,';');
js=js.replace("else if(a==='example'){query='A-13, B-07, C-03';", "else if(a==='example'){query=products.slice(0,3).map(p=>p.code).join(', ');");
js=js.replace("else if(a==='photoSample')setPhotoSample();",'');
js=js.replace("else if(a==='updateStart')runUpdate(b);",'');
js=js.replace("else if(a==='photoRemove'){", "else if(a==='photoRemove'){photoFile=null;");
// Drop the unused initial invoice illustration and browser exporter; all business I/O uses the local API.
const live=fs.readFileSync('frontend-live.js','utf8');js+='\n'+live+'\nbootstrap();\n';
new vm.Script(js);
css+='\n.real-product-image{max-width:100%;max-height:100%;object-fit:contain}.no-product-image{height:100%;min-height:46px;display:flex;flex-direction:column;align-items:center;justify-content:center;color:#aeb9c9;gap:6px}.no-product-image small{font-size:10px}.thumb img{width:100%;height:100%;object-fit:cover}.connection-error{max-width:700px;padding:60px 30px;margin:50px auto;line-height:2.3}.upload-label{cursor:pointer;display:inline-block;background:var(--accent);color:white;border-radius:8px;padding:9px 18px;font-size:13px}.product-image-editor{display:flex;align-items:flex-start;gap:20px;margin-bottom:20px}.product-image-editor>div:first-child{width:180px;height:140px;border-radius:10px;background:#f8faff;border:1px dashed #b9c9e4;display:flex;align-items:center;justify-content:center;font-size:11px;color:#a1aec0;overflow:hidden;position:relative;cursor:pointer;transition:.16s}.product-image-editor>div:first-child:hover,.product-image-editor>div:first-child.dragging{border-color:var(--accent);background:var(--soft)}.product-image-editor img{width:100%;height:100%;object-fit:contain}.product-image-empty{display:flex;flex-direction:column;gap:4px;align-items:center;justify-content:center;text-align:center;padding:14px}.product-image-empty strong{font-size:12px;color:#64748b;font-weight:500}.product-image-empty small{font-size:11px;color:#9aa6b8}.image-remove{position:absolute;top:7px;right:7px;width:24px;height:24px;border:0;border-radius:50%;padding:0;background:#d94f4f;color:#fff;font-size:19px;line-height:22px;box-shadow:0 2px 7px #7b2f2f40}.image-remove:hover{background:#bb3838;color:#fff;transform:none}.product-image-editor>.prototype-note{margin:0;padding-top:8px}.form-label{display:inline-flex;align-items:center;gap:2px}.required-mark{font-style:normal;color:#d64b4b}.import-mappings{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.import-mappings label{font-size:11px;color:#8391a6;display:flex;flex-direction:column;gap:6px}.import-mappings select{font-size:11px;width:100%}.import-result-table{max-height:45vh}.raw-ocr{font-size:12px;color:#8391a6;margin-bottom:16px}.raw-ocr pre{max-height:180px;overflow:auto;white-space:pre-wrap}.photo-main{max-width:1100px}.product-topbar button{font-size:11px}.product-topbar{display:none!important}.app{min-height:100vh}.sidebar{position:sticky;top:0;height:100vh;align-self:flex-start}.sidebar .brand{align-items:flex-start;padding-bottom:0;min-height:0}.sidebar .brand-sub{position:static;white-space:nowrap;letter-spacing:.25px;font-size:10px}.sidebar-bottom #saveState{display:block}.brand-mark{background:transparent;overflow:hidden}.brand-mark img{display:block;width:100%;height:100%}.selectedbar{left:210px}@media(max-width:1150px){.selectedbar{left:174px}}@media(max-width:800px){.import-mappings{grid-template-columns:repeat(2,1fr)}.selectedbar{left:78px}.sidebar{top:0;height:100vh}.app{min-height:100vh}.product-image-editor{display:block}.product-image-editor>div:first-child{width:100%;height:150px}.product-image-editor>.prototype-note{padding-top:9px}}';
fs.mkdirSync('web',{recursive:true});fs.writeFileSync('web/app.css',css);fs.writeFileSync('web/app.js',js);
fs.writeFileSync('web/index.html','<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>货有数 · 档口开单系统</title><link rel="stylesheet" href="/assets/app.css"></head><body><div id="app"><div style="padding:40px;font-family:Microsoft YaHei">正在连接本地服务。如果你直接打开了此页面，请关闭本页，双击“档口开单系统.exe”启动。</div></div><dialog id="dialog" class="dialog" aria-labelledby="dialogTitle"></dialog><div id="toast" class="toast hidden" role="status"></div><script src="/assets/app.js"></script></body></html>');
console.log('Production frontend generated without sample products.');
