let appReady=false,appState={},draftLastSaved='',draftSending=null,draftError=false,productImage='',photoFile=null,ocrLines=[],importSession=null,importPreview=null;
async function api(path,options={}){const headers={'X-Counter-Request':'1',...(options.headers||{})};if(options.body&&!(options.body instanceof FormData)){headers['Content-Type']='application/json';options.body=JSON.stringify(options.body)}const r=await fetch(path,{...options,headers});if(!r.ok){let err;try{err=await r.json()}catch{}throw Error(typeof err?.detail==='string'?err.detail:'操作失败（'+r.status+'），请重试')}return r.json()}
async function bootstrap(){try{appState=await api('/api/state');products=appState.products;version=appState.version;selected=new Set(appState.draft.selected||[]);quantities=appState.draft.quantities||{};draftLastSaved=JSON.stringify(draftData());appReady=true;render()}catch(e){$('#app').innerHTML='<div class="connection-error"><h2>无法连接本地服务</h2><p>'+esc(e.message)+'</p><p>请重新双击“档口开单系统.exe”打开。</p><button data-action="reload">重新连接</button></div>'}}
function draftData(){return {selected:[...selected],quantities:Object.fromEntries([...selected].map(id=>[String(id),Number.isFinite(quantities[id])?quantities[id]:products.find(p=>p.id===id)?.min||1]))}}
async function persistDraft(){if(!appReady)return;if(draftSending){await draftSending;return draftError?undefined:persistDraft()}const snapshot=JSON.stringify(draftData());if(snapshot===draftLastSaved)return;draftSending=(async()=>{try{await api('/api/draft',{method:'PUT',body:JSON.parse(snapshot)});draftLastSaved=snapshot;draftError=false}catch(e){draftError=true;toast('清单尚未保存：'+e.message)}finally{const status=$('#saveState');if(status){status.textContent=draftError?'清单未保存，请重试':'数据保存在本机';status.style.color=draftError?'#c45e42':''}}})();await draftSending;draftSending=null;if(!draftError&&JSON.stringify(draftData())!==draftLastSaved)return persistDraft()}
async function refreshProducts(){const s=await api('/api/state');products=s.products;appState=s;render()}
async function changeDataDir(){const button=$('[data-action="changeDataDir"]');if(button)button.disabled=true;try{const result=await api('/api/data-location/select',{method:'POST',body:{}});if(result.cancelled)return toast('未更改文件存储位置');toast('文件存储位置已更新，正在刷新页面');window.location.reload()}catch(e){toast(e.message)}finally{if(button)button.disabled=false}}
function review(){return ''}
function productImageMarkup(){return productImage?'<img src="/api/images/'+productImage+'" alt="产品图片"><button type="button" class="image-remove" data-action="removeProductImage" aria-label="删除产品图片">×</button>':'<div class="product-image-empty"><strong>拖拽图片到这里</strong><small>或点击选择图片</small></div>'}
function renderProductImagePreview(){const preview=$('#productImagePreview');if(preview)preview.innerHTML=productImageMarkup()}
async function uploadProductImage(file){if(!file||!file.type.startsWith('image/'))return toast('请选择 JPG、PNG 或 WEBP 图片');const button=$('[form="productForm"]');if(button)button.disabled=true;try{const fd=new FormData();fd.append('file',file);productImage=(await api('/api/images',{method:'POST',body:fd})).image;renderProductImagePreview()}catch(err){toast(err.message)}finally{if(button)button.disabled=false}}
function newForm(id){const p=products.find(p=>p.id===id)||{code:'',factoryCode:'',name:'',factory:'',area:'',size:'',battery:'',charger:'',pack:'',inner:'',volume:'',price:'',min:'',cat:'日用百货',notes:'',image:''};productImage=p.image||'';const fields=[['code','销售编码',true],['factoryCode','厂家编码',true],['name','产品名称',true],['factory','厂家名称',true],['area','厂家地区',false],['size','尺寸',false],['battery','电池容量',false],['charger','充电头 / 接口',false],['pack','装箱数（个 / 件）',false],['inner','中包数（个 / 中包）',false],['volume','单件体积（m³）',false],['price','出厂价（元 / 个）',false],['min','起订件数',false]];openDialog(id?'编辑商品资料':'新增商品','保存后写入本机数据库，关闭软件后仍会保留。','<form id="productForm" data-id="'+(id||'')+'"><div class="product-image-editor"><div id="productImagePreview" class="product-image-dropzone" data-product-image-dropzone tabindex="0" role="button" aria-label="拖拽或点击上传产品图片">'+productImageMarkup()+'</div><input type="file" id="productImageInput" accept="image/jpeg,image/png,image/webp" hidden><p class="prototype-note">拖拽图片到此处，或点击选择 · JPG / PNG / WEBP，最大 15 MB</p></div><div class="form-grid">'+fields.map(([k,l,required])=>'<label><span class="form-label">'+l+(required?' <em class="required-mark">*</em>':'')+'</span><input name="'+k+'" value="'+esc(p[k]??'')+'" '+(['pack','inner','min'].includes(k)?'type="number" min="1" max="1000000" step="1"':k==='price'?'type="number" min="0" step="0.01"':k==='volume'?'type="number" min="0" step="0.000001"':'maxlength="300"')+(required?' required':'')+'></label>').join('')+'<label><span class="form-label">商品分类</span><input name="cat" value="'+esc(p.cat||'')+'" maxlength="300"></label><label style="grid-column:1/-1"><span class="form-label">备注</span><textarea name="notes" maxlength="300">'+esc(p.notes||'')+'</textarea></label></div></form>','<small>销售编码唯一；厂家编码在同一厂家内唯一。</small><button class="primary" type="submit" form="productForm">保存商品</button>')}
async function saveProduct(form){if(!form.reportValidity())return;const button=$('[form="productForm"]');button.disabled=true;try{let data=Object.fromEntries(new FormData(form)),id=Number(form.dataset.id);data.image=productImage;for(const [k,defaultValue] of [['pack',1],['inner',1],['volume',0],['price',0],['min',1]])data[k]=data[k]===''?defaultValue:Number(data[k]);await api(id?'/api/products/'+id:'/api/products',{method:id?'PUT':'POST',body:data});closeDialog();await refreshProducts();toast('商品资料已保存到本机')}catch(e){toast(e.message)}finally{button.disabled=false}}
async function exportOrder(){const button=$('#exportButton');button.disabled=true;try{const result=await api('/api/orders',{method:'POST',body:{items:picked().map(p=>({id:p.id,quantity:qty(p)})),mode}});const a=document.createElement('a');a.href=result.url;a.download=result.filename;a.click();toast('报货单已生成，可在“导出记录”中再次下载');if(!$('#finishOrderButton')){button.insertAdjacentHTML('beforebegin','<button id="finishOrderButton" data-action="finishOrder">完成本次并清空</button>');$('#dialog .dialog-foot small').textContent='确认下载完成后，可清空本次清单。关闭弹窗保留清单。'}button.textContent='再次生成并下载'}catch(e){toast(e.message)}finally{button.disabled=false}}
function showImport(step=1){if(step===1){importSession=null;importPreview=null;openDialog('Excel 导入商品','上传厂家表格，映射字段、预览校验后再写入数据库。','<div class="upload-box">'+icon('upload')+'<h3>选择厂家商品资料表</h3><p>支持 .xlsx / .xls，最大 30 MB，每批最多 10000 行。</p><label class="upload-label">选择 Excel 文件<input id="bookInput" type="file" accept=".xlsx,.xls" hidden></label></div><div class="between" style="margin-top:18px"><small>没有现成表格？可使用系统导入模板。</small><a href="/api/import-template" class="help-link">下载导入模板</a></div><p class="prototype-note">原表不会被修改。复杂图片公式和多图行需要导入后核对；旧版 .xls 图片请手动补充。</p>','<small id="importStatus">只在本机处理文件</small><button data-action="close">取消</button>');return}if(!importPreview)return;drawImportMapping()}
async function uploadBook(file){if(!file)return;$('#importStatus').textContent='正在读取表格，请稍候…';try{const fd=new FormData();fd.append('file',file);importSession=await api('/api/import/upload',{method:'POST',body:fd});importSession.config={sheet:importSession.sheets[0],header:1,prefix:'',start:1,factory:''};importPreview=await api('/api/import/preview',{method:'POST',body:{batch:importSession.batch,...importSession.config}});importSession.config.mapping=importPreview.mapping;drawImportMapping()}catch(e){if($('#importStatus'))$('#importStatus').textContent=e.message;toast(e.message)}}
function importConfig(){const config={sheet:$('#importSheet').value,header:Number($('#importHeader').value),factory:$('#importFactory').value.trim(),prefix:$('#importPrefix').value.trim(),start:Number($('#importStart').value),mapping:{}};document.querySelectorAll('[data-import-field]').forEach(e=>{if(e.value!=='')config.mapping[e.dataset.importField]=Number(e.value)});return config}
function drawImportMapping(){const c=importSession.config;openDialog('对应表格字段','文件：'+esc(importSession.filename)+' · 字段对应后点击校验预览。','<div class="form-grid"><label>工作表<select id="importSheet">'+importSession.sheets.map(s=>'<option '+(s===c.sheet?'selected':'')+'>'+esc(s)+'</option>').join('')+'</select></label><label>表头行<input id="importHeader" type="number" min="1" max="50" value="'+c.header+'"></label></div><button data-action="importReloadHeaders" style="margin:14px 0">重新读取表头</button><div class="import-mappings">'+Object.entries(importSession.fields).map(([key,label])=>'<label>'+esc(label)+'<select data-import-field="'+key+'"><option value="">不导入 / 使用默认值</option>'+importPreview.headers.map((h,i)=>'<option value="'+i+'" '+(c.mapping[key]===i?'selected':'')+'>'+(i+1)+' · '+esc(h||'空列名')+'</option>').join('')+'</select></label>').join('')+'</div><div class="form-grid" style="margin-top:20px"><label>统一厂家名称（原表没有时填写）<input id="importFactory" value="'+esc(c.factory)+'"></label><label>销售编码前缀（原表没有时填写）<input id="importPrefix" value="'+esc(c.prefix)+'" placeholder="例如 A"></label><label>编码起始序号<input id="importStart" type="number" min="1" step="1" value="'+c.start+'"></label></div><p class="prototype-note">未填默认值：起订件数 1、中包数 1、单件体积 0；提交前请核对。价格和装箱数没有默认值，缺失行会被标记。</p>','<button data-action="import">重新选择文件</button><button class="primary" data-action="importValidate">校验并预览</button>')}
async function reloadImportHeaders(){const button=$('[data-action="importReloadHeaders"]');button.disabled=true;try{const c=importConfig();delete c.mapping;importPreview=await api('/api/import/preview',{method:'POST',body:{batch:importSession.batch,...c}});importSession.config={...c,mapping:importPreview.mapping};drawImportMapping()}catch(e){toast(e.message)}finally{button.disabled=false}}
async function validateImport(){const button=$('[data-action="importValidate"]');button.disabled=true;try{importSession.config=importConfig();importPreview=await api('/api/import/preview',{method:'POST',body:{batch:importSession.batch,...importSession.config}});openDialog('核对后导入','仅提交校验通过的行；错误和重复行会跳过，不覆盖已有资料。','<div class="import-result"><b>共 '+importPreview.total+' 行 · 可导入 '+importPreview.valid+' 行 · 问题行 '+(importPreview.total-importPreview.valid)+' 行</b></div>'+importPreview.warnings.map(w=>'<div class="notice" style="margin:10px 0">'+esc(w)+'</div>').join('')+'<div class="table-scroll import-result-table"><table><thead><tr><th>原表行</th><th>销售编码</th><th>商品名称</th><th>厂家</th><th>装箱数</th><th>单价</th><th>校验结果</th></tr></thead><tbody>'+importPreview.rows.slice(0,100).map(r=>'<tr><td>'+r.row+'</td><td>'+esc(r.data.code)+'</td><td>'+esc(r.data.name)+'</td><td>'+esc(r.data.factory)+'</td><td>'+esc(r.data.pack)+'</td><td>'+esc(r.data.price)+'</td><td style="color:'+(r.error?'#c56745':'#338a69')+'">'+esc(r.error||'可导入')+'</td></tr>').join('')+'</tbody></table></div><p class="prototype-note">仅展示前 100 行，提交处理全部 '+importPreview.total+' 行。</p>','<button data-action="importNext">返回修改</button><button data-action="importErrors">下载问题行 CSV</button><button class="primary" data-action="importCommit" '+(!importPreview.valid?'disabled':'')+'>导入有效的 '+importPreview.valid+' 行</button>')}catch(e){toast(e.message)}finally{button.disabled=false}}
async function importCommit(){const button=$('[data-action="importCommit"]');button.disabled=true;try{const r=await api('/api/import/commit',{method:'POST',body:{batch:importSession.batch,previewId:importPreview.previewId}});closeDialog();query='';factory='';category='';await refreshProducts();toast('成功导入 '+r.count+' 款商品')}catch(e){toast(e.message);button.disabled=false}}
function importErrors(){const rows=importPreview.rows.filter(r=>r.error);if(!rows.length)return toast('没有问题行');const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const fields=Object.keys(importSession.fields);const data=[['原表行','问题',...Object.values(importSession.fields)],...rows.map(r=>[r.row,r.error,...fields.map(k=>r.data[k])])].map(r=>r.map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='导入问题行.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
async function backup(){try{const files=await api('/api/backups');openDialog('数据与备份','数据目录：'+esc(appState.dataDir),'<div class="between"><div><h3>备份数据库、图片和未完成清单</h3><p class="prototype-note">每天首次启动自动备份。可下载备份到其他设备，防止本机硬盘损坏。</p></div><button class="primary" data-action="backupCreate">立即备份</button></div><div class="table-scroll" style="margin-top:20px"><table><thead><tr><th>备份文件</th><th>大小</th><th>操作</th></tr></thead><tbody>'+files.map(f=>'<tr><td>'+esc(f.name)+'</td><td>'+(f.size/1024/1024).toFixed(2)+' MB</td><td><a href="/api/backups/'+encodeURIComponent(f.name)+'">下载</a>　<button data-action="backupRestore" data-name="'+esc(f.name)+'">恢复</button></td></tr>').join('')+'</tbody></table></div>','<small>恢复前会先自动备份当前资料。</small><button data-action="close">关闭</button>')}catch(e){toast(e.message)}}
async function createBackup(){const b=$('[data-action="backupCreate"]');b.disabled=true;try{await api('/api/backups',{method:'POST'});await backup();toast('备份已完成')}catch(e){toast(e.message);b.disabled=false}}
function restorePrompt(name){openDialog('恢复备份','将恢复数据库及对应图片，当前资料会先另存一份安全备份。','<p>备份：'+esc(name)+'</p><label class="stack" style="margin-top:18px">输入“恢复备份”确认<input id="restoreConfirm" autocomplete="off"></label>','<button data-action="backup">返回</button><button class="primary" data-action="backupRestoreConfirm" data-name="'+esc(name)+'">恢复备份</button>',true)}
async function restoreBackup(name){try{await api('/api/backups/restore',{method:'POST',body:{name,confirmation:$('#restoreConfirm').value}});appReady=false;closeDialog();await bootstrap();toast('资料已从备份恢复')}catch(e){toast(e.message)}}
async function history(){try{const rows=await api('/api/orders');openDialog('导出记录','保留最近 100 次生成记录；商品修改不会改变已生成报货单。','<div class="table-scroll"><table><thead><tr><th>开单时间</th><th>商品款数</th><th>件数</th><th>文件</th></tr></thead><tbody>'+rows.map(o=>'<tr><td>'+esc(o.createdAt.replace('T',' '))+'</td><td>'+o.items.length+'</td><td>'+o.items.reduce((n,p)=>n+p.quantity,0)+'</td><td><a href="/api/exports/'+encodeURIComponent(o.file)+'">下载报货单</a></td></tr>').join('')+'</tbody></table></div>'+(!rows.length?'<div class="empty">还没有生成过报货单。</div>':''))}catch(e){toast(e.message)}}
function showUpdate(){openDialog('软件版本与维护','当前版本 '+version+' · 本地版','<div class="update-intro"><div class="update-mark">'+icon('refresh')+'</div><h2>尚未配置在线更新源</h2><p>本版本不会联网查询或安装更新。</p></div><div class="update-notes">新版本可由维护者提供完整程序包。先备份、退出旧程序，再解压新版并运行。业务数据位于独立目录，替换程序不删除商品资料。<br>自动更新需要后续配置发布地址及升级校验。</div>','<small>数据仍保存在本机</small><button class="primary" data-action="close">了解了</button>',true)}
function photoPage(){return '<div class="between page-title"><div><h1>图片开单</h1><p>识别在本机完成，不上传图片；手写内容请逐行核对。</p></div><span class="tag">'+(appState.ocrAvailable?'离线识别可用':'可手动录入')+'</span></div><div class="photo-steps"><div><span>1</span><b>上传订单图片</b><small>照片或聊天截图</small></div><i></i><div><span>2</span><b>核对识别结果</b><small>商品、数量、单位</small></div><i></i><div><span>3</span><b>确认并导出</b><small>按厂家生成报货单</small></div></div><section class="panel photo-main"><div class="between panel-head"><h3>订单图片</h3><small>JPG / PNG / WEBP · 单张不超过 15 MB</small></div><input type="file" id="orderPhotoInput" accept="image/jpeg,image/png,image/webp" hidden>'+(photoUrl?'<div class="photo-selected"><div class="between"><b>'+esc(photoName)+'</b><div class="flex"><button class="quiet" data-action="photoChoose">更换图片</button><button class="quiet" data-action="photoRemove">移除</button></div></div><div class="photo-preview" data-dropzone><img src="'+esc(photoUrl)+'" alt="订单原图" style="transform:rotate('+photoRotation+'deg)"></div><div class="between photo-tools"><small>建议先旋转到文字朝上，再开始识别。</small><button data-action="photoRotate">'+icon('refresh')+' 旋转 90°</button></div></div>':'<div class="photo-drop" data-dropzone tabindex="0" role="button" aria-label="选择或拖入订单图片" data-action="photoChoose"><div class="photo-upload-icon">'+icon('image')+'</div><h2>上传客户的订单图片</h2><p>拖入图片、点击选择文件，或直接粘贴截图</p><span class="primary-upload">'+icon('upload')+' 上传订单图片</span><small>拍正、拍清，保留商品编码和数量单位。</small></div>')+'<div class="photo-action"><div><b>先核对，再开单</b><p>潦草手写可能无法准确识别，可手动补充商品和数量。</p></div><div class="flex"><button data-action="photoManual" '+(!photoUrl?'disabled':'')+'>对照图片手动录入</button><button class="primary" data-action="photoRecognize" '+(!photoUrl||!appState.ocrAvailable?'disabled':'')+'>开始离线识别 '+icon('arrow')+'</button></div></div><div id="ocrStatus" class="photo-demo-note">仅识别你选择的这张图片，无付费调用。首次识别需要加载本机模型，可能稍慢。</div></section>'}
async function beginPhotoDemo(){if(!photoFile)return toast('请先上传订单图片');const button=$('[data-action="photoRecognize"]');button.disabled=true;$('#ocrStatus').textContent='正在本机识别，请稍候… 请勿关闭软件。';try{const fd=new FormData();fd.append('file',photoFile);const r=await api('/api/recognize?rotation='+photoRotation,{method:'POST',body:fd});ocrLines=r.lines;photoRows=r.rows.map(row=>({...row,key:++photoRowCounter}));if(!photoRows.length)photoRows=[{key:++photoRowCounter,raw:'未能可靠提取商品行，请对照原图手动补充。',id:0,quantity:0,unit:'',reviewed:false}];showPhotoConfirmation()}catch(e){toast('识别未完成：'+e.message);if($('#ocrStatus'))$('#ocrStatus').textContent='识别失败，可重试或对照图片手动录入。'}finally{button.disabled=false}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;if(a==='reload')bootstrap();else if(a==='history')history();else if(a==='changeDataDir')changeDataDir();else if(a==='importReloadHeaders')reloadImportHeaders();else if(a==='importErrors')importErrors();else if(a==='backupCreate')createBackup();else if(a==='backupRestore')restorePrompt(b.dataset.name);else if(a==='backupRestoreConfirm')restoreBackup(b.dataset.name);else if(a==='removeProductImage'){productImage='';renderProductImagePreview()}else if(a==='photoManual'){ocrLines=[];photoRows=[{key:++photoRowCounter,raw:'手动录入',id:0,quantity:1,unit:'',reviewed:false}];showPhotoConfirmation()}else if(a==='shutdown'){openDialog('退出系统','退出前会保存当前待开单清单。','<p>关闭浏览器标签页不会停止本地服务。点击下方按钮退出软件。</p>','<button data-action="close">取消</button><button class="primary" data-action="shutdownConfirm">保存并退出</button>',true)}else if(a==='shutdownConfirm'){persistDraft().then(async()=>{if(draftError)return;await api('/api/shutdown',{method:'POST'});closeDialog();appReady=false;$('#app').innerHTML='<div class="connection-error"><h2>系统已退出</h2><p>资料已保存在本机，可以关闭此页面。</p></div>'}).catch(e=>toast(e.message))}});
document.addEventListener('click',e=>{if(e.target.closest('[data-product-image-dropzone]')&&!e.target.closest('[data-action]'))$('#productImageInput')?.click()});
document.addEventListener('change',e=>{if(e.target.id==='bookInput')uploadBook(e.target.files[0]);if(e.target.id==='productImageInput')uploadProductImage(e.target.files[0])});
document.addEventListener('dragover',e=>{const zone=e.target.closest('[data-product-image-dropzone]');if(!zone)return;e.preventDefault();zone.classList.add('dragging')});
document.addEventListener('dragleave',e=>{const zone=e.target.closest('[data-product-image-dropzone]');if(zone&&!zone.contains(e.relatedTarget))zone.classList.remove('dragging')});
document.addEventListener('drop',e=>{const zone=e.target.closest('[data-product-image-dropzone]');if(!zone)return;e.preventDefault();zone.classList.remove('dragging');uploadProductImage(e.dataTransfer.files[0])});
document.addEventListener('input',e=>{if(e.target.dataset.qty)persistDraft()});
window.addEventListener('pagehide',()=>{if(appReady&&JSON.stringify(draftData())!==draftLastSaved)fetch('/api/draft',{method:'PUT',keepalive:true,headers:{'Content-Type':'application/json','X-Counter-Request':'1'},body:JSON.stringify(draftData())}).catch(()=>{})});
const legacyRender=render;
render=function(){legacyRender();document.querySelector('.batch-example')?.remove();const helper=document.querySelector('.library-helper');if(helper){const label=helper.querySelector('label');const target=document.querySelector('.panel-head .flex:last-child');if(label&&target)target.insertBefore(label,target.firstChild);helper.remove()}};
