let appReady=false,appState={},draftLastSaved='',draftSending=null,draftError=false,productImage='',photoFile=null,ocrLines=[],importSession=null,importPreview=null,dirBrowserPath='';
async function api(path,options={}){const headers={'X-Counter-Request':'1',...(options.headers||{})};if(options.body&&!(options.body instanceof FormData)){headers['Content-Type']='application/json';options.body=JSON.stringify(options.body)}const r=await fetch(path,{...options,headers});if(!r.ok){let err;try{err=await r.json()}catch{}throw Error(typeof err?.detail==='string'?err.detail:'操作失败（'+r.status+'），请重试')}return r.json()}
async function bootstrap(){try{appState=await api('/api/state');products=appState.products;version=appState.version;selected=new Set(appState.draft.selected||[]);quantities=appState.draft.quantities||{};draftLastSaved=JSON.stringify(draftData());appReady=true;render();if(appState.needsDataLocation)setTimeout(()=>openDataDirBrowser(''),120)}catch(e){$('#app').innerHTML='<div class="connection-error"><h2>无法连接本地服务</h2><p>'+esc(e.message)+'</p><p>请重新双击“档口开单系统.exe”打开。</p><button data-action="reload">重新连接</button></div>'}}
function draftData(){return {selected:[...selected],quantities:Object.fromEntries([...selected].map(id=>[String(id),Number.isFinite(quantities[id])?quantities[id]:1]))}}
async function persistDraft(){if(!appReady)return;if(draftSending){await draftSending;return draftError?undefined:persistDraft()}const snapshot=JSON.stringify(draftData());if(snapshot===draftLastSaved)return;draftSending=(async()=>{try{await api('/api/draft',{method:'PUT',body:JSON.parse(snapshot)});draftLastSaved=snapshot;draftError=false}catch(e){draftError=true;toast('清单尚未保存：'+e.message)}finally{const status=$('#saveState');if(status){status.textContent=draftError?'清单未保存，请重试':'数据保存在本机';status.style.color=draftError?'#c45e42':''}}})();await draftSending;draftSending=null;if(!draftError&&JSON.stringify(draftData())!==draftLastSaved)return persistDraft()}
async function refreshProducts(){const s=await api('/api/state');products=s.products;appState=s;render()}
function changeDataDir(){dirBrowserPath='';openDataDirBrowser('')}
function dirBrowserEntry(item){return '<button class="dir-entry" data-action="dirOpen" data-path="'+esc(item.path)+'"><span class="dir-entry-icon">'+icon('folder')+'</span><span class="dir-entry-name">'+esc(item.name)+'</span><span class="dir-entry-arrow">›</span></button>'}
async function openDataDirBrowser(path=''){try{const result=await api('/api/data-location/browse?path='+encodeURIComponent(path||''));dirBrowserPath=result.path||'';const shortcutMarkup=(result.shortcuts||[]).map(dirBrowserEntry).join('')||'<div class="dir-empty-shortcuts">未找到常用文件夹</div>';const rootMarkup=(result.roots||[]).map(dirBrowserEntry).join('');const entryMarkup=(result.entries||[]).map(dirBrowserEntry).join('')||'<div class="dir-empty">当前文件夹没有子文件夹，可以直接选择此文件夹。</div>';const current=result.path||'此电脑';const atRoot=!result.path;openDialog('选择文件存储位置','首次进入也可以从这里选择，后续点击编辑图标可随时更改。','<div class="dir-browser"><div class="dir-toolbar"><button class="quiet" data-action="dirUp" '+(result.parent?'':'disabled')+'>‹ 上一级</button><div class="dir-current" title="'+esc(current)+'">'+esc(current)+'</div></div><div class="dir-layout"><aside class="dir-shortcuts"><b>快速访问</b>'+shortcutMarkup+'<b class="dir-section-title">磁盘</b>'+rootMarkup+'</aside><section class="dir-main"><div class="dir-list">'+(atRoot?(rootMarkup||'<div class="dir-empty">没有找到可用磁盘。</div>'):entryMarkup)+'</div>'+(!atRoot?'<div class="dir-new"><input id="dirNewName" placeholder="新建文件夹名称" maxlength="80"><button data-action="dirNew">新建文件夹</button></div>':'')+'</section></div><p class="prototype-note">请选择一个空文件夹。系统会复制数据库、商品图片、备份和导出记录，原目录不会删除。</p></div>','<small class="dir-selected-hint">'+(atRoot?'先打开一个磁盘或文件夹':'将选择当前显示的文件夹')+'</small><button data-action="close">取消</button><button class="primary" data-action="dataDirSelect" '+(atRoot?'disabled':'')+'>选择此文件夹</button>',true)}catch(e){toast(e.message)}}
async function createDataDirFolder(){const input=$('#dirNewName'),button=$('[data-action="dirNew"]');if(!input?.value.trim())return toast('请输入文件夹名称');button.disabled=true;try{await api('/api/data-location/create-folder',{method:'POST',body:{parent:dirBrowserPath,name:input.value.trim()}});toast('文件夹已创建');await openDataDirBrowser(dirBrowserPath)}catch(e){toast(e.message)}finally{button.disabled=false}}
async function selectDataDir(){if(!dirBrowserPath)return toast('请先打开要保存数据的文件夹');const button=$('[data-action="dataDirSelect"]');button.disabled=true;try{await api('/api/data-location/set',{method:'POST',body:{path:dirBrowserPath}});closeDialog();toast('文件存储位置已更新，正在刷新页面');setTimeout(()=>window.location.reload(),250)}catch(e){toast(e.message);button.disabled=false}}
function review(){return ''}
async function exportOrder(){const button=$('#exportButton');const columns=selectedExportColumns();if(!columns.length)return toast('请至少选择一个导出字段');button.disabled=true;try{const result=await api('/api/orders',{method:'POST',body:{items:picked().map(p=>({id:p.id,quantity:qty(p)})),mode,columns}});appState.exportColumns=columns;const a=document.createElement('a');a.href=result.url;a.download=result.filename;a.click();toast('报货单已生成，可在“导出记录”中再次下载');if(!$('#finishOrderButton')){button.insertAdjacentHTML('beforebegin','<button id="finishOrderButton" data-action="finishOrder">完成本次并清空</button>');$('#dialog .dialog-foot small').textContent='确认下载完成后，可清空本次清单。关闭弹窗保留清单。'}button.textContent='再次生成并下载'}catch(e){toast(e.message)}finally{button.disabled=false}}
function showImport(step=1){if(step===1){importSession=null;importPreview=null;openDialog('Excel 导入商品','上传厂家表格，映射字段、预览校验后再写入数据库。','<div class="upload-box" data-import-dropzone>'+icon('upload')+'<h3>将厂家表格拖到这里</h3><p>或点击下方按钮选择 · .xlsx / .xls · 最大 500 MB · 每批最多 10000 行</p><label class="upload-label">选择 Excel 文件<input id="bookInput" type="file" accept=".xlsx,.xls" hidden></label></div><div class="between" style="margin-top:18px"><small>没有现成表格？可使用系统导入模板。</small><a href="/api/import-template" class="help-link">下载导入模板</a></div><p class="prototype-note">原表不会被修改。复杂图片公式和多图行需要导入后核对；旧版 .xls 图片请手动补充。</p>','<small id="importStatus">只在本机处理文件</small><button data-action="close">取消</button>');return}if(!importPreview)return;drawImportMapping()}
let importUploading=false;
async function uploadBook(file){
 if(!file||importUploading)return;
 if(!/\.(xlsx|xls)$/i.test(file.name))return toast('请选择 .xlsx 或 .xls 文件');
 if(file.size>500*1024*1024)return toast('Excel 文件超过 500 MB，请拆分后导入');
 importUploading=true;
 const status=$('#importStatus'),input=$('#bookInput'),zone=$('[data-import-dropzone]');
 if(input)input.disabled=true;if(zone)zone.setAttribute('aria-busy','true');
 if(status)status.textContent='正在本机读取 '+(file.size/1024/1024).toFixed(1)+' MB 表格，大文件需要一些时间…';
 try{
  const fd=new FormData();fd.append('file',file);
  const session=await api('/api/import/upload',{method:'POST',body:fd});
  session.config={sheet:session.sheets[0],header:1,prefix:'',start:1,factory:''};
  const preview=await api('/api/import/preview',{method:'POST',body:{batch:session.batch,...session.config}});
  if(!status?.isConnected)return;
  importSession=session;importPreview=preview;session.config.mapping=preview.mapping;drawImportMapping();
 }catch(e){if(status?.isConnected)status.textContent=e.message;toast(e.message)}
 finally{importUploading=false;if(input){input.disabled=false;input.value=''}if(zone)zone.removeAttribute('aria-busy')}
}

function importConfig(){const config={sheet:$('#importSheet').value,header:Number($('#importHeader').value),factory:$('#importFactory').value.trim(),prefix:$('#importPrefix').value.trim(),start:Number($('#importStart').value),mapping:{}};document.querySelectorAll('[data-import-field]').forEach(e=>{if(e.value!=='')config.mapping[e.dataset.importField]=Number(e.value)});return config}
function drawImportMapping(){
 const c=importSession.config,required=['code','factoryCode','name'];
 const orderedKeys=[...required,...Object.keys(importSession.fields).filter(key=>!required.includes(key))];
 const fields=orderedKeys.map(key=>{const label=importSession.fields[key];return '<label><span class="form-label">'+esc(label)+(required.includes(key)?' <em class="required-mark">*</em>':'')+'</span><select aria-label="'+esc(label)+'" data-import-field="'+key+'"><option value=""></option>'+importPreview.headers.map((h,i)=>'<option value="'+i+'" '+(c.mapping[key]===i?'selected':'')+'>'+(i+1)+' · '+esc(h||'空列名')+'</option>').join('')+'</select></label>'}).join('');
 openDialog('对应表格字段','文件：'+esc(importSession.filename),
 '<section class="import-section"><h3>数据读取</h3><div class="import-source-row"><label>工作表<select id="importSheet">'+importSession.sheets.map(s=>'<option '+(s===c.sheet?'selected':'')+'>'+esc(s)+'</option>').join('')+'</select></label><label>表头行<input id="importHeader" type="number" min="1" max="50" value="'+c.header+'"></label><button data-action="importReloadHeaders">重新读取表头</button></div></section>'+
 '<section class="import-section"><div class="import-section-heading"><h3>字段匹配</h3><small><em class="required-mark">*</em> 必填；销售编码、厂家名称可在下方补充</small></div><div class="import-mappings">'+fields+'</div></section>'+
 '<section class="import-section"><h3>信息补充</h3><div class="import-supplement"><label>统一厂家名称<input id="importFactory" value="'+esc(c.factory)+'" placeholder="原表缺少时补充"></label><label>销售编码前缀<input id="importPrefix" value="'+esc(c.prefix)+'" placeholder="例如 A" maxlength="12"></label><label>编码起始序号<input id="importStart" type="number" min="1" step="1" value="'+c.start+'"></label></div><p class="import-hint">仅补充原表空值。前缀 A、序号 1 → A-01、A-02…；已有编码保留，重复编码会提示。</p></section>',
 '<button data-action="import">重新选择文件</button><button class="primary" data-action="importValidate">校验并预览</button>');
}

async function reloadImportHeaders(){const button=$('[data-action="importReloadHeaders"]');button.disabled=true;try{const c=importConfig();delete c.mapping;importPreview=await api('/api/import/preview',{method:'POST',body:{batch:importSession.batch,...c}});importSession.config={...c,mapping:importPreview.mapping};drawImportMapping()}catch(e){toast(e.message)}finally{button.disabled=false}}
async function validateImport(){const button=$('[data-action="importValidate"]');button.disabled=true;try{importSession.config=importConfig();importPreview=await api('/api/import/preview',{method:'POST',body:{batch:importSession.batch,...importSession.config}});openDialog('核对后导入','仅提交校验通过的行；错误和重复行会跳过，不覆盖已有资料。','<div class="import-result"><b>共 '+importPreview.total+' 行 · 可导入 '+importPreview.valid+' 行 · 问题行 '+(importPreview.total-importPreview.valid)+' 行</b></div>'+importPreview.warnings.map(w=>'<div class="notice" style="margin:10px 0">'+esc(w)+'</div>').join('')+'<div class="table-scroll import-result-table"><table><thead><tr><th>原表行</th><th>销售编码</th><th>商品名称</th><th>厂家</th><th>装箱数</th><th>单价</th><th>校验结果</th></tr></thead><tbody>'+importPreview.rows.slice(0,100).map(r=>'<tr><td>'+r.row+'</td><td>'+esc(r.data.code)+'</td><td>'+esc(r.data.name)+'</td><td>'+esc(r.data.factory)+'</td><td>'+esc(r.data.pack)+'</td><td>'+esc(r.data.price)+'</td><td style="color:'+(r.error?'#c56745':'#338a69')+'">'+esc(r.error||'可导入')+'</td></tr>').join('')+'</tbody></table></div><p class="prototype-note">仅展示前 100 行，提交处理全部 '+importPreview.total+' 行。</p>','<button data-action="importNext">返回修改</button><button data-action="importErrors">下载问题行 CSV</button><button class="primary" data-action="importCommit" '+(!importPreview.valid?'disabled':'')+'>导入有效的 '+importPreview.valid+' 行</button>')}catch(e){toast(e.message)}finally{button.disabled=false}}
async function importCommit(){const button=$('[data-action="importCommit"]');button.disabled=true;try{const r=await api('/api/import/commit',{method:'POST',body:{batch:importSession.batch,previewId:importPreview.previewId}});closeDialog();query='';factory='';category='';await refreshProducts();toast('成功导入 '+r.count+' 款商品')}catch(e){toast(e.message);button.disabled=false}}
function importErrors(){const rows=importPreview.rows.filter(r=>r.error);if(!rows.length)return toast('没有问题行');const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const fields=Object.keys(importSession.fields);const data=[['原表行','问题',...Object.values(importSession.fields)],...rows.map(r=>[r.row,r.error,...fields.map(k=>r.data[k])])].map(r=>r.map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='导入问题行.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
async function backup(){try{const files=await api('/api/backups');openDialog('数据与备份','数据目录：'+esc(appState.dataDir),'<div class="between"><div><h3>备份数据库、图片和未完成清单</h3><p class="prototype-note">每天首次启动自动备份。可下载备份到其他设备，防止本机硬盘损坏。</p></div><button class="primary" data-action="backupCreate">立即备份</button></div><div class="table-scroll" style="margin-top:20px"><table><thead><tr><th>备份文件</th><th>大小</th><th>操作</th></tr></thead><tbody>'+files.map(f=>'<tr><td>'+esc(f.name)+'</td><td>'+(f.size/1024/1024).toFixed(2)+' MB</td><td><a href="/api/backups/'+encodeURIComponent(f.name)+'">下载</a>　<button data-action="backupRestore" data-name="'+esc(f.name)+'">恢复</button></td></tr>').join('')+'</tbody></table></div>','<small>恢复前会先自动备份当前资料。</small><button data-action="close">关闭</button>')}catch(e){toast(e.message)}}
async function createBackup(){const b=$('[data-action="backupCreate"]');b.disabled=true;try{await api('/api/backups',{method:'POST'});await backup();toast('备份已完成')}catch(e){toast(e.message);b.disabled=false}}
function restorePrompt(name){openDialog('恢复备份','将恢复数据库及对应图片，当前资料会先另存一份安全备份。','<p>备份：'+esc(name)+'</p><label class="stack" style="margin-top:18px">输入“恢复备份”确认<input id="restoreConfirm" autocomplete="off"></label>','<button data-action="backup">返回</button><button class="primary" data-action="backupRestoreConfirm" data-name="'+esc(name)+'">恢复备份</button>',true)}
async function restoreBackup(name){try{await api('/api/backups/restore',{method:'POST',body:{name,confirmation:$('#restoreConfirm').value}});appReady=false;closeDialog();await bootstrap();toast('资料已从备份恢复')}catch(e){toast(e.message)}}
async function history(){try{const rows=await api('/api/orders');openDialog('导出记录','保留最近 100 次生成记录；商品修改不会改变已生成报货单。','<div class="table-scroll"><table><thead><tr><th>开单时间</th><th>商品款数</th><th>件数</th><th>文件</th></tr></thead><tbody>'+rows.map(o=>'<tr><td>'+esc(o.createdAt.replace('T',' '))+'</td><td>'+o.items.length+'</td><td>'+o.items.reduce((n,p)=>n+p.quantity,0)+'</td><td><a href="/api/exports/'+encodeURIComponent(o.file)+'">下载报货单</a></td></tr>').join('')+'</tbody></table></div>'+(!rows.length?'<div class="empty">还没有生成过报货单。</div>':''))}catch(e){toast(e.message)}}
async function deletionHistory(){try{const rows=await api('/api/deletion-logs');openDialog('删除日志','记录商品资料的删除时间和当时的商品信息。','<div class="table-scroll deletion-history"><table><thead><tr><th>删除时间</th><th>销售编码</th><th>商品名称</th><th>厂家名称</th></tr></thead><tbody>'+rows.map(row=>'<tr><td>'+esc(row.deletedAt.replace('T',' '))+'</td><td class="mono">'+esc(row.code)+'</td><td>'+esc(row.name)+'</td><td>'+esc(row.factory||'—')+'</td></tr>').join('')+'</tbody></table></div>'+(!rows.length?'<div class="empty">还没有商品删除记录。</div>':''))}catch(e){toast(e.message)}}
async function showUpdate(){openDialog('检查软件更新','正在连接 GitHub Releases…','<div class="update-intro"><div class="update-mark">'+icon('refresh')+'</div><h2>正在检查最新版本</h2><p>只读取公开版本信息，不会上传商品资料。</p></div>','<small>当前版本 '+version+'</small><button class="primary" data-action="close">取消</button>',true);try{const info=await api('/api/update/check');if(info.status==='ok'&&info.updateAvailable){const size=info.package?.bytes?((info.package.bytes/1024/1024).toFixed(1)+' MB'):'大小未知';openDialog('发现新版本','当前版本 '+esc(info.currentVersion)+' · 最新版本 '+esc(info.latestVersion),'<div class="update-intro"><div class="update-mark">'+icon('refresh')+'</div><h2>'+esc(info.releaseName||('版本 '+info.latestVersion))+'</h2><p>更新包约 '+size+'，发布于 '+esc((info.publishedAt||'').slice(0,10)||'未知日期')+'</p></div><div class="update-notes">'+(info.notes?esc(info.notes).replace(/\r?\n/g,'<br>'):'本次更新暂无说明')+'</div><p class="prototype-note">当前阶段先提供可信版本检查和下载地址；自动关闭旧程序、替换文件并重启将在更新助手接入后启用。商品资料、图片和已选择的数据目录不会被更新包覆盖。</p>','<small>来源：GitHub Releases</small><a class="primary" href="'+esc(info.package.url)+'" target="_blank" rel="noreferrer">下载更新包</a>',true)}else if(info.status==='no-release'){openDialog('软件版本与维护','当前版本 '+version+' · GitHub Releases','<div class="update-intro"><div class="update-mark">'+icon('check')+'</div><h2>暂未发布在线更新</h2><p>当前版本已经是本机可用版本。</p></div><div class="update-notes">发布新版本后，这里会显示版本号、更新说明和下载入口。</div>','<small>更新源已配置</small><button class="primary" data-action="close">知道了</button>',true)}else{openDialog('软件版本与维护','当前版本 '+version+' · GitHub Releases','<div class="update-intro"><div class="update-mark">'+icon('refresh')+'</div><h2>暂时无法完成检查</h2><p>'+esc(info.message||'更新服务暂时不可用')+'</p></div><div class="update-notes">请稍后重试。商品资料和图片不会受到影响。</div>','<small>更新源：GitHub Releases</small><button class="primary" data-action="close">知道了</button>',true)}}catch(e){openDialog('软件版本与维护','当前版本 '+version,'<div class="update-intro"><div class="update-mark">'+icon('refresh')+'</div><h2>暂时无法完成检查</h2><p>'+esc(e.message)+'</p></div><div class="update-notes">请稍后重试。商品资料和图片不会受到影响。</div>','<small>更新源：GitHub Releases</small><button class="primary" data-action="close">知道了</button>',true)}}
function photoPage(){return '<div class="between page-title"><div><h1>图片开单</h1><p>识别在本机完成，不上传图片；手写内容请逐行核对。</p></div><span class="tag">'+(appState.ocrAvailable?'离线识别可用':'可手动录入')+'</span></div><div class="photo-steps"><div><span>1</span><b>上传订单图片</b><small>照片或聊天截图</small></div><i></i><div><span>2</span><b>核对识别结果</b><small>商品、数量、单位</small></div><i></i><div><span>3</span><b>确认并导出</b><small>按厂家生成报货单</small></div></div><section class="panel photo-main"><div class="between panel-head"><h3>订单图片</h3><small>JPG / PNG / WEBP · 单张不超过 15 MB</small></div><input type="file" id="orderPhotoInput" accept="image/jpeg,image/png,image/webp" hidden>'+(photoUrl?'<div class="photo-selected"><div class="between"><b>'+esc(photoName)+'</b><div class="flex"><button class="quiet" data-action="photoChoose">更换图片</button><button class="quiet" data-action="photoRemove">移除</button></div></div><div class="photo-preview" data-dropzone><img src="'+esc(photoUrl)+'" alt="订单原图" style="transform:rotate('+photoRotation+'deg)"></div><div class="between photo-tools"><small>建议先旋转到文字朝上，再开始识别。</small><button data-action="photoRotate">'+icon('refresh')+' 旋转 90°</button></div></div>':'<div class="photo-drop" data-dropzone tabindex="0" role="button" aria-label="选择或拖入订单图片" data-action="photoChoose"><div class="photo-upload-icon">'+icon('image')+'</div><h2>上传客户的订单图片</h2><p>拖入图片、点击选择文件，或直接粘贴截图</p><span class="primary-upload">'+icon('upload')+' 上传订单图片</span><small>拍正、拍清，保留商品编码和数量单位。</small></div>')+'<div class="photo-action"><div><b>先核对，再开单</b><p>潦草手写可能无法准确识别，可手动补充商品和数量。</p></div><div class="flex"><button data-action="photoManual" '+(!photoUrl?'disabled':'')+'>对照图片手动录入</button><button class="primary" data-action="photoRecognize" '+(!photoUrl||!appState.ocrAvailable?'disabled':'')+'>开始离线识别 '+icon('arrow')+'</button></div></div><div id="ocrStatus" class="photo-demo-note">仅识别你选择的这张图片，无付费调用。首次识别需要加载本机模型，可能稍慢。</div></section>'}
async function beginPhotoDemo(){if(!photoFile)return toast('请先上传订单图片');const button=$('[data-action="photoRecognize"]');button.disabled=true;$('#ocrStatus').textContent='正在本机识别，请稍候… 请勿关闭软件。';try{const fd=new FormData();fd.append('file',photoFile);const r=await api('/api/recognize?rotation='+photoRotation,{method:'POST',body:fd});ocrLines=r.lines;photoRows=r.rows.map(row=>({...row,key:++photoRowCounter}));if(!photoRows.length)photoRows=[{key:++photoRowCounter,raw:'未能可靠提取商品行，请对照原图手动补充。',id:0,quantity:0,unit:'',reviewed:false}];showPhotoConfirmation()}catch(e){toast('识别未完成：'+e.message);if($('#ocrStatus'))$('#ocrStatus').textContent='识别失败，可重试或对照图片手动录入。'}finally{button.disabled=false}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;if(a==='reload')bootstrap();else if(a==='history')history();else if(a==='deletionHistory')deletionHistory();else if(a==='changeDataDir')changeDataDir();else if(a==='dirOpen')openDataDirBrowser(b.dataset.path||'');else if(a==='dirUp')openDataDirBrowser(dirBrowserPath?dirBrowserPath.replace(/[\\/]?[^\\/]+[\\/]?$/,''):'');else if(a==='dirNew')createDataDirFolder();else if(a==='dataDirSelect')selectDataDir();else if(a==='importReloadHeaders')reloadImportHeaders();else if(a==='importErrors')importErrors();else if(a==='backupCreate')createBackup();else if(a==='backupRestore')restorePrompt(b.dataset.name);else if(a==='backupRestoreConfirm')restoreBackup(b.dataset.name);else if(a==='photoManual'){ocrLines=[];photoRows=[{key:++photoRowCounter,raw:'手动录入',id:0,quantity:1,unit:'',reviewed:false}];showPhotoConfirmation()}else if(a==='shutdown'){openDialog('退出系统','退出前会保存当前待开单清单。','<p>关闭浏览器标签页不会停止本地服务。点击下方按钮退出软件。</p>','<button data-action="close">取消</button><button class="primary" data-action="shutdownConfirm">保存并退出</button>',true)}else if(a==='shutdownConfirm'){persistDraft().then(async()=>{if(draftError)return;await api('/api/shutdown',{method:'POST'});closeDialog();appReady=false;$('#app').innerHTML='<div class="connection-error"><h2>系统已退出</h2><p>资料已保存在本机，可以关闭此页面。</p></div>'}).catch(e=>toast(e.message))}});
document.addEventListener('change',e=>{if(e.target.id==='bookInput')uploadBook(e.target.files[0])});
document.addEventListener('input',e=>{if(e.target.dataset.qty)persistDraft()});
window.addEventListener('pagehide',()=>{if(appReady&&JSON.stringify(draftData())!==draftLastSaved)fetch('/api/draft',{method:'PUT',keepalive:true,headers:{'Content-Type':'application/json','X-Counter-Request':'1'},body:JSON.stringify(draftData())}).catch(()=>{})});
const legacyRender=render;
render=function(){legacyRender();document.querySelector('.batch-example')?.remove();const helper=document.querySelector('.library-helper');if(helper){const label=helper.querySelector('label');const target=document.querySelector('.panel-head .flex:last-child');if(label&&target)target.insertBefore(label,target.firstChild);helper.remove()}};

document.addEventListener('dragover',e=>{const zone=e.target.closest('[data-import-dropzone]');if(!zone)return;e.preventDefault();e.dataTransfer.dropEffect=importUploading?'none':'copy';zone.classList.add('dragging')});
document.addEventListener('dragleave',e=>{const zone=e.target.closest('[data-import-dropzone]');if(zone&&!zone.contains(e.relatedTarget))zone.classList.remove('dragging')});
document.addEventListener('drop',e=>{const zone=e.target.closest('[data-import-dropzone]');if(!zone)return;e.preventDefault();zone.classList.remove('dragging');if(e.dataTransfer.files.length!==1)return toast('请每次导入一个 Excel 文件');uploadBook(e.dataTransfer.files[0])});

// 正式版本统一交付安装程序；重复安装会覆盖固定程序目录并保留独立数据目录。
async function showUpdate(){openDialog('检查软件更新','正在连接 GitHub Releases…','<div class="update-intro"><div class="update-mark">'+icon('refresh')+'</div><h2>正在检查最新版本</h2><p>只读取公开版本信息，不会上传商品资料。</p></div>','<small>当前版本 '+version+'</small><button class="primary" data-action="close">取消</button>',true);try{const info=await api('/api/update/check');if(info.status==='ok'&&info.updateAvailable){const size=info.package?.bytes?((info.package.bytes/1024/1024).toFixed(1)+' MB'):'大小未知';openDialog('发现新版本','当前版本 '+esc(info.currentVersion)+' · 最新版本 '+esc(info.latestVersion),'<div class="update-intro"><div class="update-mark">'+icon('refresh')+'</div><h2>'+esc(info.releaseName||('版本 '+info.latestVersion))+'</h2><p>安装程序约 '+size+'，发布于 '+esc((info.publishedAt||'').slice(0,10)||'未知日期')+'</p></div><div class="update-notes">'+(info.notes?esc(info.notes).replace(/\r?\n/g,'<br>'):'本次更新暂无说明')+'</div><p class="prototype-note">下载完成后先退出当前软件，再运行安装程序。它会覆盖同一程序目录并更新桌面图标，商品资料、图片和数据目录会保留。</p>','<small>来源：GitHub Releases</small><a class="primary" href="'+esc(info.package.url)+'" target="_blank" rel="noreferrer">下载安装程序</a>',true)}else if(info.status==='no-release'){openDialog('软件版本与维护','当前版本 '+version+' · GitHub Releases','<div class="update-intro"><div class="update-mark">'+icon('check')+'</div><h2>暂未发布在线更新</h2><p>当前版本已经是本机可用版本。</p></div><div class="update-notes">发布新版本后，这里会显示版本号、更新说明和安装程序下载入口。</div>','<small>更新源已配置</small><button class="primary" data-action="close">知道了</button>',true)}else{openDialog('软件版本与维护','当前版本 '+version+' · GitHub Releases','<div class="update-intro"><div class="update-mark">'+icon('refresh')+'</div><h2>暂时无法完成检查</h2><p>'+esc(info.message||'更新服务暂时不可用')+'</p></div><div class="update-notes">请稍后重试。商品资料和图片不会受到影响。</div>','<small>更新源：GitHub Releases</small><button class="primary" data-action="close">知道了</button>',true)}}catch(e){openDialog('软件版本与维护','当前版本 '+version,'<div class="update-intro"><div class="update-mark">'+icon('refresh')+'</div><h2>暂时无法完成检查</h2><p>'+esc(e.message)+'</p></div><div class="update-notes">请稍后重试。商品资料和图片不会受到影响。</div>','<small>更新源：GitHub Releases</small><button class="primary" data-action="close">知道了</button>',true)}}
if(new URLSearchParams(location.search).get('updated')==='1')setTimeout(()=>{if(typeof toast==='function'&&version)toast('更新完成，已启动新版本 v'+version)},1800);
