
'use strict';
const paths={image:'M3 3h18v18H3ZM3 17l6-6 4 4 3-3 5 5M8 7h.01',search:'M21 21l-5-5M10.5 18a7.5 7.5 0 1 0 0-15 7.5 7.5 0 0 0 0 15',box:'m3 7 9-5 9 5v10l-9 5-9-5ZM3 7l9 5 9-5M12 12v10M7 4.8l10 5.5',grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',file:'M14 2H5v20h14V7ZM14 2v6h5M8 13h8M8 17h8',upload:'M12 16V3m-5 5 5-5 5 5M3 15v6h18v-6',plus:'M12 4v16M4 12h16',refresh:'M20 8a8 8 0 0 0-14-3L3 8m0-5v5h5M4 16a8 8 0 0 0 14 3l-3 3m0 5v-5h-5',shield:'m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6ZM8 12l3 3 5-6',factory:'M3 21V9l6 4V7l6 4V3h6v18ZM6 17h2m3 0h2m3 0h2',check:'m5 12 4 4L20 5',arrow:'M4 12h16m-6-6 6 6-6 6',clock:'M12 8v5l4 2M22 12a10 10 0 1 0-20 0 10 10 0 0 0 20 0',trash:'M4 7h16M9 7V4h6v3m3 0-1 14H7L6 7m4 4v6m4-6v6',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',edit:'M4 16.5V20h3.5L19 8.5 15.5 5 4 16.5ZM13.8 6.7l3.5 3.5'};
paths.folder='M3 6h7l2 2h9v11H3Z';paths.refresh='M20 8a8 8 0 0 0-14-3L3 8m0-5v5h5M4 16a8 8 0 0 0 14 3l-3 3m0 5v-5h-5';
function icon(n){return '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="'+(paths[n]||paths.box)+'"/></svg>'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const initial=[
{id:1,code:'A-13',factoryCode:'XFS12138',name:'便携折叠小风扇',cat:'生活电器',factory:'新风尚电器厂',area:'浙江 · 慈溪',size:'16 × 8 × 4 cm',battery:'1200 mAh',charger:'Type-C / 不含充电头',pack:60,inner:12,volume:.085,price:12.5,min:2,type:'fan',color:'#ddeae2'},
{id:2,code:'A-16',factoryCode:'XFS12086',name:'桌面静音循环扇',cat:'生活电器',factory:'新风尚电器厂',area:'浙江 · 慈溪',size:'18 × 15 × 24 cm',battery:'2000 mAh',charger:'USB / 不含充电头',pack:24,inner:6,volume:.12,price:26,min:1,type:'deskfan',color:'#eee4d5'},
{id:3,code:'B-07',factoryCode:'MK8806',name:'奶油色保温杯 · 500mL',cat:'日用百货',factory:'麦可日用品厂',area:'浙江 · 永康',size:'7 × 7 × 22 cm',battery:'不适用',charger:'不适用',pack:48,inner:12,volume:.064,price:18.8,min:1,type:'cup',color:'#eee6dc'},
{id:4,code:'B-12',factoryCode:'MK9012',name:'便携分格收纳盒',cat:'日用百货',factory:'麦可日用品厂',area:'浙江 · 永康',size:'24 × 16 × 12 cm',battery:'不适用',charger:'不适用',pack:36,inner:6,volume:.16,price:8.6,min:2,type:'storage',color:'#dfe8ef'},
{id:5,code:'C-03',factoryCode:'YL6030',name:'触控柔光小夜灯',cat:'生活电器',factory:'悦亮照明厂',area:'广东 · 中山',size:'10 × 10 × 15 cm',battery:'800 mAh',charger:'Type-C / 不含充电头',pack:80,inner:20,volume:.072,price:9.9,min:1,type:'lamp',color:'#ece4eb'},
{id:6,code:'C-08',factoryCode:'YL6082',name:'折叠护眼台灯',cat:'生活电器',factory:'悦亮照明厂',area:'广东 · 中山',size:'12 × 12 × 32 cm',battery:'1800 mAh',charger:'5V 1A / 含充电头',pack:30,inner:5,volume:.098,price:22,min:1,type:'desklamp',color:'#e3e6ed'},
{id:7,code:'D-21',factoryCode:'JT2315',name:'硅胶按摩洗头刷',cat:'清洁用品',factory:'佳腾塑业',area:'浙江 · 台州',size:'8 × 8 × 7 cm',battery:'不适用',charger:'不适用',pack:120,inner:20,volume:.05,price:3.2,min:3,type:'brush',color:'#e1e9e2'},
{id:8,code:'D-26',factoryCode:'JT2510',name:'长柄除尘清洁刷',cat:'清洁用品',factory:'佳腾塑业',area:'浙江 · 台州',size:'32 × 6 × 4 cm',battery:'不适用',charger:'不适用',pack:100,inner:10,volume:.092,price:4.5,min:2,type:'longbrush',color:'#ebe4dc'}];
let products=[],selected=new Set(),viewMode='list',theme='a',query='',factory='',category='',quantities={},mode='single',version='1.0.0',updateTimer=null,toastTimer=null,importStep=1,importDone=false,lastFocus=null;
const $=s=>document.querySelector(s),money=n=>'¥'+Number(n).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
function productMedia(p,key,label){const main=Array.isArray(p.images)?p.images:(p.image?[p.image]:[]),boxes=Array.isArray(p.boxImages)?p.boxImages:[],list=key==='boxImages'?boxes:main,name=list[0]||'',count=list.length;return name?'<div class="product-art-media"><img class="real-product-image" src="/api/images/'+esc(name)+'" alt="'+esc(label)+'"><span class="media-count" aria-label="'+count+'张'+esc(label)+'">'+count+'</span></div>':'<div class="no-product-image">'+icon('image')+'<small>暂无'+esc(label)+'</small></div>'} function art(p){return productMedia(p,'images','主图')} function boxThumb(p){return '<div class="thumb product-box-thumb">'+productMedia(p,'boxImages','彩盒')+'</div>'}
function thumb(p){return '<div class="thumb" style="background:'+'#f3f6fa'+'">'+art(p)+'</div>'}
function toast(s){$('#toast').textContent=s;$('#toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),3400)}
function picked(){return products.filter(p=>selected.has(p.id))}
function tokens(){return query.trim().toUpperCase().split(/[\s,，;；、]+/).filter(Boolean)}
function result(){let t=tokens();return products.filter(p=>(!factory||p.factory===factory)&&(!category||p.cat===category)&&(!t.length||(t.length>1?t.includes(p.code.toUpperCase()):[p.code,p.name,p.factoryCode,p.factory].some(x=>x.toUpperCase().includes(t[0])))))}
function missing(){let t=tokens();return t.length>1?t.filter(x=>!products.some(p=>p.code.toUpperCase()===x)):[]}
function factoryOptions(){return '<option value="">全部厂家</option>'+[...new Set(products.map(p=>p.factory))].map(f=>'<option '+(factory===f?'selected':'')+'>'+esc(f)+'</option>').join('')}
function logo(){return '<div class="brand"><span class="brand-mark" aria-hidden="true"><img src="/assets/brand-mark.svg" alt=""></span><div><div class="brand-name">货有数</div><div class="brand-sub">档口开单系统</div></div></div>'}
function side(){return '<aside class="sidebar">'+logo()+'<div class="nav-group"><nav class="nav"><button class="'+(activePage==='products'?'active':'')+'" data-action="all">'+icon('grid')+'<span class="nav-text">商品资料</span></button><button class="'+(activePage==='photo'?'active':'')+'" data-action="photo">'+icon('image')+'<span class="nav-text">图片开单</span></button><button data-action="suppliers">'+icon('factory')+'<span class="nav-text">厂家信息</span></button><button data-action="history">'+icon('clock')+'<span class="nav-text">导出记录</span></button><button data-action="deletionHistory">'+icon('trash')+'<span class="nav-text">删除日志</span></button></nav></div><div class="sidebar-bottom"><span id="saveState"><i class="dot"></i> 数据存储在本机</span><button class="quiet" data-action="backup">'+icon('shield')+' 数据与备份</button><button class="quiet" data-action="update">'+icon('refresh')+' 检查更新 <small>v'+version+'</small></button></div></aside>'}
function title(){return '<div class="between page-title library-title"><div><h1>商品资料库</h1><div class="storage-location"><span>文件存储位置</span><code>'+esc(appState.dataDir||'本机数据目录')+'</code><button class="storage-edit" data-action="changeDataDir" title="更改文件存储位置" aria-label="更改文件存储位置">'+icon('edit')+'</button></div></div><div class="flex"><button data-action="import">'+icon('upload')+' Excel 导入</button><button class="primary" data-action="new">'+icon('plus')+' 新增商品</button></div></div>'}
function stats(){let items=[['在售商品',products.length,'款','box'],['合作厂家',new Set(products.map(p=>p.factory)).size,'家','factory'],['销售编码覆盖','100','%','check']];return '<div class="stats">'+items.map(a=>'<div class="stat"><div><small>'+a[0]+'</small><b>'+a[1]+' <small>'+a[2]+'</small></b></div><span class="stat-icon">'+icon(a[3])+'</span></div>').join('')+'</div>'}
function searchbar(){return '<div class="searchbar"><div class="searchfield">'+icon('search')+'<input id="search" aria-label="搜索商品" placeholder="搜索销售编码、商品名称，多个编码用空格或逗号分隔" value="'+esc(query)+'"></div><button class="primary" data-action="search">查询</button><select id="factory" aria-label="厂家筛选">'+factoryOptions()+'</select><button data-action="reset" title="清空筛选">重置</button></div>'}
function missingHtml(){let m=missing();return m.length?'<div class="notice">有 '+m.length+' 个销售编码未找到：<b>'+m.map(esc).join('、')+'</b>。请核对编码后重新查询。</div>':''}
function table(){let rows=result();return '<div class="panel"><div class="between panel-head"><div class="flex"><h3>商品资料</h3><span class="tag">'+products.length+' 款</span></div><div class="flex"><button class="help-link batch-example" data-action="example">试试批量查询 →</button><div class="view-switch" role="group" aria-label="商品显示模式"><button data-action="viewMode" data-view="list" aria-pressed="'+(viewMode==='list')+'" class="'+(viewMode==='list'?'active':'')+'">'+icon('file')+' 列表</button><button data-action="viewMode" data-view="grid" aria-pressed="'+(viewMode==='grid')+'" class="'+(viewMode==='grid'?'active':'')+'">'+icon('grid')+' 大图</button></div></div></div>'+searchbar()+missingHtml()+'<div class="library-helper between"><span>支持多个销售编码同时查询 · 切换筛选或显示模式，已选商品仍保留</span>'+(viewMode==='grid'?'<label class="flex"><input type="checkbox" id="selectAll" aria-label="选择当前结果" '+(rows.length&&rows.every(p=>selected.has(p.id))?'checked':'')+'>选择当前结果</label>':'')+'</div>'+(viewMode==='list'?'<div class="table-scroll"><table><thead><tr><th><input type="checkbox" id="selectAll" aria-label="选择当前结果" '+(rows.length&&rows.every(p=>selected.has(p.id))?'checked':'')+'></th><th>销售编码</th><th>商品 / 规格</th><th>厂家编码</th><th>供货厂家</th><th>装箱数</th><th>出厂价 / 个</th><th>彩盒</th><th>操作</th></tr></thead><tbody>'+rows.map(p=>'<tr class="'+(selected.has(p.id)?'selected':'')+'"><td><input type="checkbox" data-select="'+p.id+'" aria-label="选择 '+esc(p.code)+'" '+(selected.has(p.id)?'checked':'')+'></td><td><b class="mono code">'+esc(p.code)+'</b></td><td><div class="product-cell">'+thumb(p)+'<div><strong>'+esc(p.name)+'</strong><small>'+esc(p.size)+'</small></div></div></td><td class="mono" style="color:#8c96a5">'+esc(p.factoryCode)+'</td><td>'+esc(p.factory)+'</td><td>'+p.pack+' <small>个 / 件</small></td><td class="price">'+money(p.price)+'</td><td>'+boxThumb(p)+'</td><td><button class="quiet help-link" data-action="detail" data-id="'+p.id+'">详情</button><button class="quiet help-link" data-action="edit" data-id="'+p.id+'">修改</button><button class="quiet help-link danger" data-action="productDelete" data-id="'+p.id+'">删除</button></td></tr>').join('')+'</tbody></table></div>':cardGrid(rows))+(!rows.length?empty():'')+'<div class="table-footer"><span>当前 '+rows.length+' 款 / 全部 '+products.length+' 款</span><span>本次已选 '+selected.size+' 款</span></div></div>'}
function empty(){return '<div class="empty">'+icon('search')+'<h3>没有找到匹配商品</h3><p>检查销售编码，或清空厂家筛选后再试试。</p><button style="margin-top:15px" data-action="reset">清空筛选</button></div>'}
function selectedbar(){return '<div class="selectedbar"><div class="flex"><span class="selection-count">'+selected.size+'</span><div><b>'+(selected.size?'款商品待开单':'还没有选择商品')+'</b><br><small>'+(selected.size?'来自 '+new Set(picked().map(p=>p.factory)).size+' 家厂家 · 同一商品只计 1 款':'勾选商品后，可统一填写件数并生成报货单')+'</small></div>'+(selected.size?'<button class="quiet" data-action="pending">查看清单</button><button class="quiet" data-action="clear">清空</button>':'')+'</div><button class="primary" data-action="order" '+(!selected.size?'disabled':'')+'>开报货单 '+icon('arrow')+'</button></div>'}
function cardGrid(rows){return '<div class="catalog-grid library-grid">'+rows.map(p=>'<article class="product-card '+(selected.has(p.id)?'chosen':'')+'"><label class="card-check"><input type="checkbox" data-select="'+p.id+'" aria-label="选择 '+esc(p.code)+'" '+(selected.has(p.id)?'checked':'')+'></label><div class="card-visual" style="background:'+'#f3f6fa'+'" data-action="detail" data-id="'+p.id+'" tabindex="0" role="button" aria-label="查看 '+esc(p.code)+' 详情">'+art(p)+'</div><div class="card-info"><div class="between"><b class="mono code">'+esc(p.code)+'</b><span class="price">'+money(p.price)+'<small> / 个</small></span></div><h3>'+esc(p.name)+'</h3><div class="card-meta">'+p.pack+' 个 / 件</div><div class="card-end"><div><small>'+esc(p.factory)+'</small><br><small class="mono">'+esc(p.factoryCode)+'</small></div><button data-action="detail" data-id="'+p.id+'">商品详情</button><button data-action="edit" data-id="'+p.id+'">修改</button><button class="quiet help-link danger" data-action="productDelete" data-id="'+p.id+'">删除</button></div></div></article>').join('')+'</div>'}
function render(){if(!appReady)return;document.body.className='theme-a';$('#app').innerHTML=review()+'<div class="app">'+side()+'<main class="workspace">'+(activePage==='photo'?photoPage():title()+stats()+table())+'</main>'+(activePage==='products'?selectedbar():'')+'</div>';const all=$('#selectAll');if(all){let rows=result(),count=rows.filter(p=>selected.has(p.id)).length;all.indeterminate=count>0&&count<rows.length}persistDraft()}
function openDialog(title,sub,content,foot='',small=false){lastFocus=document.activeElement;const d=$('#dialog');d.className='dialog'+(small?' small':'');d.innerHTML='<div class="dialog-head"><div><h2 id="dialogTitle">'+title+'</h2>'+(sub?'<small>'+sub+'</small>':'')+'</div><button data-action="close" aria-label="关闭弹窗">×</button></div><div class="dialog-body">'+content+'</div>'+(foot?'<div class="dialog-foot">'+foot+'</div>':'');if(!d.open)d.showModal()}
function closeDialog(){if(updateTimer){clearInterval(updateTimer);updateTimer=null}$('#dialog').close();if(lastFocus?.isConnected)lastFocus.focus()}
function qty(p){return quantities[p.id]??1}
function total(){return picked().reduce((a,p)=>{let q=qty(p);a.cases+=q;a.units+=q*p.pack;a.amount+=q*p.pack*p.price;a.volume+=q*p.volume;return a},{cases:0,units:0,amount:0,volume:0})}
function order(){if(!selected.size)return toast('请先选择需要开单的商品');mode='single';for(const p of picked())if(!Number.isInteger(quantities[p.id])||quantities[p.id]<1)quantities[p.id]=1;openDialog('生成厂家报货单','第 2 步 · 填写件数，确认导出方式','<div class="notice" style="margin:0 0 18px">当前按 1 件＝1 箱；总数量＝件数 × 装箱数。总金额按单价计算。</div><div class="table-scroll"><table class="order-table"><thead><tr><th>商品 / 销售编码</th><th>厂家 / 厂家编码</th><th>装箱数</th><th>订货件数</th><th>总数量</th><th>总金额</th></tr></thead><tbody>'+picked().map(p=>'<tr><td>'+esc(p.name)+'<br><small class="mono">'+esc(p.code)+'</small></td><td>'+esc(p.factory)+'<br><small class="mono">'+esc(p.factoryCode)+'</small></td><td>'+p.pack+' 个</td><td><input type="number" min="'+1+'" step="1" data-qty="'+p.id+'" aria-label="'+esc(p.code)+' 订货件数" value="'+qty(p)+'"><br><small id="qtyError'+p.id+'">请输入正整数</small></td><td id="units'+p.id+'"></td><td id="amount'+p.id+'" class="price"></td></tr>').join('')+'</tbody></table></div><div class="order-settings"><div class="section-label">跨厂家导出方式</div><div class="radio-cards"><label class="radio-card"><input type="radio" name="exportMode" value="single" checked><div><b>生成一个 Excel</b><small>按厂家分工作表，方便自己统一核对。</small></div></label><label class="radio-card"><input type="radio" name="exportMode" value="multiple"><div><b>每个厂家一个 Excel</b><small>打包成 ZIP 下载，解压后分别发给厂家。</small></div></label></div><p id="exportHint" class="prototype-note" style="margin-top:10px"></p></div><div class="totals" id="orderTotals"></div>','<small>下载生成的报货单，不会自动发送给厂家。</small><button id="exportButton" class="primary" data-action="export">'+icon('file')+' 生成并下载</button>');refreshOrder()}
function refreshOrder(){let valid=true;for(const p of picked()){let q=qty(p),ok=Number.isInteger(q)&&q>=1&&q<=1000000;valid&&=ok;$('#qtyError'+p.id).className=ok?'':'bad';$('#qtyError'+p.id).textContent=ok?'请输入正整数':'请输入 ≥'+1+' 的整数（≤100万）';$('#units'+p.id).textContent=ok?q*p.pack+' 个':'—';$('#amount'+p.id).textContent=ok?money(q*p.pack*p.price):'—'}let t=total();$('#orderTotals').innerHTML=[['商品款数',selected.size,'款'],['订货件数',valid?t.cases:'—','件'],['商品总数量',valid?t.units:'—','个'],['总体积',valid?t.volume.toFixed(3):'—','m³'],['采购总金额',valid?money(t.amount):'—','']].map(x=>'<div><small>'+x[0]+'</small><strong>'+x[1]+'<span>'+x[2]+'</span></strong></div>').join('');$('#exportButton').disabled=!valid;let count=new Set(picked().map(p=>p.factory)).size;$('#exportHint').textContent=mode==='single'?'将生成 1 个文件，包含 '+count+' 张厂家工作表。合并文件包含全部厂家的采购信息，转发前请注意选择。':'将生成 '+count+' 个 Excel 文件，以 1 个 ZIP 压缩包下载。'}
function suppliers(){const supplierNames=[...new Set(products.map(p=>p.factory).filter(Boolean))];if(!supplierNames.length){openDialog('合作厂家','','<div class="empty"><h3>暂无厂家</h3><p>请先在商品资料中维护厂家信息。</p></div>');return}openDialog('合作厂家','选择厂家后查看对应商品','<div class="stack">'+supplierNames.map(f=>{let ps=products.filter(p=>p.factory===f);return '<div class="panel" style="padding:18px"><div class="between"><div><h3>'+esc(f)+'</h3><small>'+ps.length+' 款商品</small></div><button data-action="filterFactory" data-factory="'+esc(f)+'">查看商品</button></div></div>'}).join('')+'</div>')}

function countInfo(){openDialog('“本次待开单”怎么统计？','统计当前这一次准备报货的商品清单。','<div class="count-example"><small>例如勾选 A-13 和 B-07</small><h2>2 款商品 · 2 家厂家</h2><p>即使每款订了多件，这里仍然计为 2 款。</p></div><div class="count-rules"><p><b>加入：</b>勾选或从商品详情加入，同一商品只计 1 款。</p><p><b>保留：</b>切换搜索、厂家筛选、列表 / 大图，已选商品都保留。</p><p><b>减少：</b>取消勾选或从清单移除；点击“清空”归零。</p><p><b>完成：</b>下载报货单后点击“完成本次并清空”，开始下一单。</p></div><p class="prototype-note">不统计历史订单；件数、总数量在开单弹窗中单独计算。未完成清单会保存在本机，关闭重开后可继续。</p>','<small>当前已选 '+selected.size+' 款商品</small><button class="primary" data-action="close">明白了</button>',true)}
function showPending(){openDialog('本次待开单清单','共 '+selected.size+' 款商品 · '+new Set(picked().map(p=>p.factory)).size+' 家厂家 · 包含当前筛选未展示的已选商品','<div class="stack">'+(picked().map(p=>'<div class="pending-item">'+thumb(p)+'<div class="grow"><b class="mono code">'+esc(p.code)+'</b><h3>'+esc(p.name)+'</h3><small>'+esc(p.factory)+'</small></div><button class="quiet danger" data-action="pendingRemove" data-id="'+p.id+'">移除</button></div>').join('')||'<div class="empty">清单为空，返回商品资料继续选货。</div>')+'</div>','<button data-action="close">继续选货</button><button class="primary" data-action="pendingOrder" '+(!selected.size?'disabled':'')+'>填写件数并开单</button>',true)}

let activePage='products',photoUrl='',photoName='',photoRotation=0,photoRows=[],photoRowCounter=0;
async function loadOrderPhoto(file){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type))return toast('请选择 JPG、PNG 或 WEBP 图片');if(file.size>15*1024*1024)return toast('图片超过 15 MB，请压缩后再上传');const next=URL.createObjectURL(file);try{await new Promise((resolve,reject)=>{const im=new Image();im.onload=resolve;im.onerror=reject;im.src=next});if(photoUrl.startsWith('blob:'))URL.revokeObjectURL(photoUrl);photoFile=file;photoUrl=next;photoName=file.name;photoRotation=0;photoRows=[];render();toast('图片已载入，可继续体验识别确认流程')}catch{URL.revokeObjectURL(next);toast('图片无法读取，请换一张清晰完整的图片')}}
function photoResult(r){const p=products.find(p=>p.id===r.id);if(!p)return {ok:false,text:'未匹配商品，请手动选择。'};if(!r.unit)return {ok:false,text:'数量单位不明，请对照原图确认。'};if(!Number.isInteger(r.quantity)||r.quantity<=0||r.quantity>1000000)return {ok:false,text:'数量须为 1～100 万的整数。'};const cases=r.unit==='个'?r.quantity/p.pack:r.quantity;if(!Number.isInteger(cases))return {ok:false,text:r.quantity+' 个不足整件（每件 '+p.pack+' 个），请核对数量。'};return {ok:true,p,cases,units:cases*p.pack,text:cases+' 件 × '+p.pack+' 个/件 = '+cases*p.pack+' 个'} }
function photoTotals(){let groups=new Map(),problems=0,unreviewed=0;for(const r of photoRows){const calc=photoResult(r);if(!calc.ok){problems++;continue}if(!r.reviewed)unreviewed++;groups.set(r.id,(groups.get(r.id)||0)+calc.cases)}let minimums=[...groups].filter(([id,q])=>q<1||q>1000000);return {groups,problems,unreviewed,minimums,valid:photoRows.length>0&&!problems&&!unreviewed&&!minimums.length}}
function photoRowMarkup(r,index){return '<article class="ocr-row" data-photo-row="'+r.key+'"><div class="between"><b class="ocr-row-title">第 '+(index+1)+' 行</b><button class="quiet danger" data-action="photoRowRemove" data-key="'+r.key+'">移除</button></div><div class="ocr-source"><span>识别原文</span><b>'+esc(r.raw||'手动补充')+'</b></div><label class="ocr-label">对应商品<select data-photo-field="id" data-key="'+r.key+'" aria-label="第 '+(index+1)+' 行对应商品"><option value="0">未匹配 · 请选择商品</option>'+products.map(p=>'<option value="'+p.id+'" '+(r.id===p.id?'selected':'')+'>'+esc(p.code+' · '+p.name+' / '+p.factory)+'</option>').join('')+'</select></label><div class="ocr-inputs"><label class="ocr-label">数量<input type="number" min="1" step="1" max="1000000" data-photo-field="quantity" data-key="'+r.key+'" value="'+r.quantity+'" aria-label="第 '+(index+1)+' 行数量"></label><label class="ocr-label">单位<select data-photo-field="unit" data-key="'+r.key+'" aria-label="第 '+(index+1)+' 行单位">'+[['','待确认'],['件','件 / 箱'],['个','个']].map(([v,t])=>'<option value="'+v+'" '+(r.unit===v?'selected':'')+'>'+t+'</option>').join('')+'</select></label><div class="ocr-converted" id="photoCalc'+r.key+'"></div></div><div class="between ocr-checkline"><span class="tag" id="photoTag'+r.key+'"></span><label><input type="checkbox" data-photo-field="reviewed" data-key="'+r.key+'" '+(r.reviewed?'checked':'')+'> 已核对商品、数量和单位</label></div></article>'}
function showPhotoConfirmation(){openDialog('报单确认','图片开单 · 先核对商品和数量，再选择按厂家导出。','<div class="ocr-demo-banner">离线识别结果需要人工核对，可能漏行或错字。请对照原图检查并补充，不能直接作为下单依据。</div><details class="raw-ocr"><summary>查看全部识别原文</summary><pre>'+esc(ocrLines.map(l=>l.text).join('\n')||'无识别原文，可手动录入')+'</pre></details><div class="ocr-layout"><aside class="ocr-original"><div class="between"><b>订单原图</b><div class="flex"><button class="quiet" data-action="photoZoom">放大</button><button class="quiet" data-action="photoConfirmRotate" aria-label="旋转订单原图">'+icon('refresh')+'</button></div></div><div class="ocr-image"><img src="'+esc(photoUrl)+'" alt="供逐行核对的订单原图" style="transform:rotate('+photoRotation+'deg)"></div><small>'+esc(photoName)+'</small><p>对照原图逐行核对。无法确定的内容，修正或移除后再继续。</p></aside><section class="ocr-results"><div class="between ocr-results-head"><h3>商品与数量</h3><span id="photoIssueSummary"></span></div>'+photoRows.map(photoRowMarkup).join('')+(!photoRows.length?'<div class="empty">已移除全部行，可手动补充商品。</div>':'')+'<button class="wide photo-add-row" data-action="photoRowAdd">＋ 补充一行商品</button><div id="photoMinimums"></div><div class="ocr-overwrite">'+(selected.size?'当前待开单中已有 '+selected.size+' 款商品。确认后将用本张图片的清单替换；取消不会改变原清单。':'确认后将加入本次待开单；同一商品出现多行时，件数合并统计。')+'</div></section></div>','<button data-action="close">返回图片</button><small id="photoConfirmSummary"></small><button class="primary" id="photoApplyButton" data-action="photoApply" disabled>'+(selected.size?'替换清单并继续':'确认商品与数量')+' '+icon('arrow')+'</button>');$('#dialog').classList.add('photo-dialog');updatePhotoSummary()}
function updatePhotoSummary(){const totals=photoTotals();for(const r of photoRows){const calc=photoResult(r),bad=calc.ok&&totals.minimums.some(([id])=>id===r.id),tag=$('#photoTag'+r.key),line=$('#photoCalc'+r.key);line.textContent=calc.text;line.classList.toggle('invalid',!calc.ok);tag.textContent=!calc.ok?'待修正':bad?'数量超出上限':r.reviewed?'已核对':'待人工核对';tag.classList.toggle('needs-review',!calc.ok||!r.reviewed||bad);const box=$('[data-photo-field="reviewed"][data-key="'+r.key+'"]');box.disabled=!calc.ok;box.checked=r.reviewed&&calc.ok}$('#photoIssueSummary').textContent=totals.problems+totals.unreviewed+totals.minimums.length?'请完成核对':'全部核对完成';$('#photoMinimums').innerHTML=totals.minimums.map(([id,q])=>{let p=products.find(p=>p.id===id);return '<div class="notice" style="margin:10px 0">'+esc(p.code)+' 合计 '+q+' 件；'+(q>1000000?'超出 100 万件上限。':'最低 请输入正整数，请核对数量。')+'</div>'}).join('');let cases=[...totals.groups.values()].reduce((a,b)=>a+b,0);$('#photoConfirmSummary').textContent=totals.problems?'还有 '+totals.problems+' 行需要修正商品或数量':totals.unreviewed?'还有 '+totals.unreviewed+' 行未勾选核对':totals.minimums.length?'请修正件数上限':'共 '+totals.groups.size+' 款商品 · '+cases+' 件';$('#photoApplyButton').disabled=!totals.valid}
function applyPhotoOrder(){const t=photoTotals();if(!t.valid)return toast('请先修正问题并逐行确认');selected=new Set(t.groups.keys());quantities=Object.fromEntries(t.groups);closeDialog();render();order();$('#dialogTitle').textContent='报单确认 · 数量与导出';$('#dialog .dialog-head small').textContent='来自图片开单 · 已人工核对商品与数量，可再次调整后导出。'}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;if(a==='photo'){activePage='photo';render()}else if(a==='photoChoose')$('#orderPhotoInput').click();else if(a==='photoRemove'){photoFile=null;if(photoUrl.startsWith('blob:'))URL.revokeObjectURL(photoUrl);photoUrl='';photoName='';photoRows=[];render()}else if(a==='photoRotate'){photoRotation=(photoRotation+90)%360;render()}else if(a==='photoRecognize')beginPhotoDemo();else if(a==='photoConfirmRotate'){photoRotation=(photoRotation+90)%360;$('#dialog .ocr-image img').style.transform='rotate('+photoRotation+'deg)'}else if(a==='photoZoom'){openDialog('查看订单原图','可对照照片核对手写内容。','<div class="photo-zoom"><img src="'+esc(photoUrl)+'" alt="订单原图"></div>','<small>原图按原始方向展示</small><button class="primary" data-action="photoReturnConfirm">返回核对</button>');$('#dialog').classList.add('photo-dialog')}else if(a==='photoReturnConfirm')showPhotoConfirmation();else if(a==='photoRowRemove'){photoRows=photoRows.filter(r=>r.key!==Number(b.dataset.key));showPhotoConfirmation()}else if(a==='photoRowAdd'){photoRows.push({key:++photoRowCounter,raw:'手动补充',id:0,quantity:1,unit:'',reviewed:false});showPhotoConfirmation()}else if(a==='photoApply')applyPhotoOrder()});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='orderPhotoInput')loadOrderPhoto(t.files[0]);if(t.dataset.photoField){const r=photoRows.find(r=>r.key===Number(t.dataset.key));if(!r)return;if(t.dataset.photoField==='reviewed')r.reviewed=t.checked;else if(t.dataset.photoField==='id'){r.id=Number(t.value);r.reviewed=false}else if(t.dataset.photoField==='unit'){r.unit=t.value;r.reviewed=false}updatePhotoSummary()}});
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.photoField==='quantity'){const r=photoRows.find(r=>r.key===Number(t.dataset.key));r.quantity=t.value===''?0:Number(t.value);r.reviewed=false;updatePhotoSummary()}});
document.addEventListener('dragover',e=>{if(activePage==='photo'&&!$('#dialog').open){e.preventDefault();e.target.closest('[data-dropzone]')?.classList.add('dragging')}});
document.addEventListener('dragleave',e=>e.target.closest?.('[data-dropzone]')?.classList.remove('dragging'));
document.addEventListener('drop',e=>{if(activePage==='photo'&&!$('#dialog').open){e.preventDefault();loadOrderPhoto(e.dataTransfer.files[0])}});
document.addEventListener('paste',e=>{if(activePage==='photo'&&!$('#dialog').open){const file=[...e.clipboardData.items].find(x=>x.kind==='file'&&x.type.startsWith('image/'))?.getAsFile();if(file){e.preventDefault();loadOrderPhoto(file)}}});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.photo-drop')){e.preventDefault();$('#orderPhotoInput').click()}});

document.addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(!b||b.disabled)return;let a=b.dataset.action,id=Number(b.dataset.id);if(a==='viewMode'){viewMode=b.dataset.view;render()}else if(a==='pending')showPending();else if(a==='countInfo')countInfo();else if(a==='pendingRemove'){selected.delete(id);render();showPending()}else if(a==='pendingOrder'){closeDialog();order()}else if(a==='finishOrder'){selected.clear();quantities={};closeDialog();render();toast('本次开单已完成，待开单清单已清空')}else if(a==='close')closeDialog();else if(a==='all'||a==='reset'){activePage='products';query='';factory='';category='';render()}else if(a==='search'){query=($('#search')||$('#batchSearch')).value;render()}else if(a==='example'){query=products.slice(0,3).map(p=>p.code).join(', ');factory='';category='';render()}else if(a==='cat'){category=b.dataset.cat;render()}else if(a==='clear'){selected.clear();render()}else if(a==='toggle'){selected.has(id)?selected.delete(id):selected.add(id);render()}else if(a==='addAll'){result().forEach(p=>selected.add(p.id));render()}else if(a==='detail')detail(id);else if(a==='detailPick'){selected.has(id)?selected.delete(id):selected.add(id);closeDialog();render()}else if(a==='new'||a==='edit')newForm(a==='edit'?id:0);else if(a==='order')order();else if(a==='export')exportOrder();else if(a==='import')showImport(1);else if(a==='importNext')showImport(2);else if(a==='importValidate')validateImport();else if(a==='importCommit')importCommit();else if(a==='update')showUpdate();else if(a==='backup')backup();else if(a==='suppliers')suppliers();else if(a==='filterFactory'){activePage='products';factory=b.dataset.factory;query='';category='';closeDialog();render()}});
document.addEventListener('change',e=>{let t=e.target;if(t.dataset.select){let id=Number(t.dataset.select);t.checked?selected.add(id):selected.delete(id);render()}else if(t.id==='selectAll'){result().forEach(p=>t.checked?selected.add(p.id):selected.delete(p.id));render()}else if(t.id==='factory'){factory=t.value;render()}else if(t.name==='exportMode'){mode=t.value;refreshOrder()}});
document.addEventListener('input',e=>{let t=e.target;if(t.dataset.qty){quantities[t.dataset.qty]=t.value===''?NaN:Number(t.value);refreshOrder()}if(t.id==='search'||t.id==='batchSearch')query=t.value});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='search'){query=e.target.value;render()}else if((e.key==='Enter'||e.key===' ')&&e.target.classList.contains('card-visual')){e.preventDefault();detail(Number(e.target.dataset.id))}});
document.addEventListener('submit',e=>{if(e.target.id==='productForm'){e.preventDefault();saveProduct(e.target)}});$('#dialog').addEventListener('cancel',()=>{if(updateTimer){clearInterval(updateTimer);updateTimer=null}});
let appReady=false,appState={},draftLastSaved='',draftSending=null,draftError=false,productImage='',photoFile=null,ocrLines=[],importSession=null,importPreview=null,dirBrowserPath='';
async function api(path,options={}){const headers={'X-Counter-Request':'1',...(options.headers||{})};if(options.body&&!(options.body instanceof FormData)){headers['Content-Type']='application/json';options.body=JSON.stringify(options.body)}const r=await fetch(path,{...options,headers});if(!r.ok){let err;try{err=await r.json()}catch{}throw Error(typeof err?.detail==='string'?err.detail:'操作失败（'+r.status+'），请重试')}return r.json()}
async function bootstrap(){try{appState=await api('/api/state');products=appState.products;version=appState.version;selected=new Set(appState.draft.selected||[]);quantities=appState.draft.quantities||{};draftLastSaved=JSON.stringify(draftData());appReady=true;render();if(appState.needsDataLocation)setTimeout(()=>openDataDirBrowser(''),120)}catch(e){$('#app').innerHTML='<div class="connection-error"><h2>无法连接本地服务</h2><p>'+esc(e.message)+'</p><p>请重新双击“档口开单系统.exe”打开。</p><button data-action="reload">重新连接</button></div>'}}
function draftData(){return {selected:[...selected],quantities:Object.fromEntries([...selected].map(id=>[String(id),Number.isFinite(quantities[id])?quantities[id]:1]))}}
async function persistDraft(){if(!appReady)return;if(draftSending){await draftSending;return draftError?undefined:persistDraft()}const snapshot=JSON.stringify(draftData());if(snapshot===draftLastSaved)return;draftSending=(async()=>{try{await api('/api/draft',{method:'PUT',body:JSON.parse(snapshot)});draftLastSaved=snapshot;draftError=false}catch(e){draftError=true;toast('清单尚未保存：'+e.message)}finally{const status=$('#saveState');if(status){status.textContent=draftError?'清单未保存，请重试':'数据保存在本机';status.style.color=draftError?'#c45e42':''}}})();await draftSending;draftSending=null;if(!draftError&&JSON.stringify(draftData())!==draftLastSaved)return persistDraft()}
async function refreshProducts(){const s=await api('/api/state');products=s.products;appState=s;render()}
function changeDataDir(){dirBrowserPath='';openDataDirBrowser('')}
function dirBrowserEntry(item){return '<button class="dir-entry" data-action="dirOpen" data-path="'+esc(item.path)+'"><span class="dir-entry-icon">'+icon('folder')+'</span><span class="dir-entry-name">'+esc(item.name)+'</span><span class="dir-entry-arrow">›</span></button>'}
async function openDataDirBrowser(path=''){try{const result=await api('/api/data-location/browse?path='+encodeURIComponent(path||''));dirBrowserPath=result.path||'';const shortcutMarkup=(result.shortcuts||[]).map(dirBrowserEntry).join('')||'<div class="dir-empty-shortcuts">未找到常用文件夹</div>';const rootMarkup=(result.roots||[]).map(dirBrowserEntry).join('');const entryMarkup=(result.entries||[]).map(dirBrowserEntry).join('')||'<div class="dir-empty">当前文件夹没有子文件夹，可以直接选择此文件夹。</div>';const current=result.path||'此电脑';const atRoot=!result.path;openDialog('选择文件存储位置','首次进入也可以从这里选择，后续点击编辑图标可随时更改。','<div class="dir-browser"><div class="dir-toolbar"><button class="quiet" data-action="dirUp" '+(result.parent?'':'disabled')+'>‹ 上一级</button><div class="dir-current" title="'+esc(current)+'">'+esc(current)+'</div></div><div class="dir-layout"><aside class="dir-shortcuts"><b>快速访问</b>'+shortcutMarkup+'<b class="dir-section-title">磁盘</b>'+rootMarkup+'</aside><section class="dir-main"><div class="dir-list">'+(atRoot?(rootMarkup||'<div class="dir-empty">没有找到可用磁盘。</div>'):entryMarkup)+'</div>'+(!atRoot?'<div class="dir-new"><input id="dirNewName" placeholder="新建文件夹名称" maxlength="80"><button data-action="dirNew">新建文件夹</button></div>':'')+'</section></div><p class="prototype-note">请选择一个空文件夹。系统会复制数据库、商品图片、备份和导出记录，原目录不会删除。</p></div>','<small class="dir-selected-hint">'+(atRoot?'先打开一个磁盘或文件夹':'将选择当前显示的文件夹')+'</small><button data-action="close">取消</button><button class="primary" data-action="dataDirSelect" '+(atRoot?'disabled':'')+'>选择此文件夹</button>',true)}catch(e){toast(e.message)}}
async function createDataDirFolder(){const input=$('#dirNewName'),button=$('[data-action="dirNew"]');if(!input?.value.trim())return toast('请输入文件夹名称');button.disabled=true;try{await api('/api/data-location/create-folder',{method:'POST',body:{parent:dirBrowserPath,name:input.value.trim()}});toast('文件夹已创建');await openDataDirBrowser(dirBrowserPath)}catch(e){toast(e.message)}finally{button.disabled=false}}
async function selectDataDir(){if(!dirBrowserPath)return toast('请先打开要保存数据的文件夹');const button=$('[data-action="dataDirSelect"]');button.disabled=true;try{await api('/api/data-location/set',{method:'POST',body:{path:dirBrowserPath}});closeDialog();toast('文件存储位置已更新，正在刷新页面');setTimeout(()=>window.location.reload(),250)}catch(e){toast(e.message);button.disabled=false}}
function review(){return ''}
async function exportOrder(){const button=$('#exportButton');const columns=selectedExportColumns();if(!columns.length)return toast('请至少选择一个导出字段');button.disabled=true;try{const result=await api('/api/orders',{method:'POST',body:{items:picked().map(p=>({id:p.id,quantity:qty(p)})),mode,columns}});appState.exportColumns=columns;const a=document.createElement('a');a.href=result.url;a.download=result.filename;a.click();toast('报货单已生成，可在“导出记录”中再次下载');if(!$('#finishOrderButton')){button.insertAdjacentHTML('beforebegin','<button id="finishOrderButton" data-action="finishOrder">完成本次并清空</button>');$('#dialog .dialog-foot small').textContent='确认下载完成后，可清空本次清单。关闭弹窗保留清单。'}button.textContent='再次生成并下载'}catch(e){toast(e.message)}finally{button.disabled=false}}
function showImport(step=1){if(step===1){importSession=null;importPreview=null;openDialog('Excel 导入商品','上传厂家表格，映射字段、预览校验后再写入数据库。','<div class="upload-box" data-import-dropzone>'+icon('upload')+'<h3>将厂家表格拖到这里</h3><p>或点击下方按钮选择 · .xlsx / .xls · 最大 500 MB · 每批最多 10000 行</p><label class="upload-label">选择 Excel 文件<input id="bookInput" type="file" accept=".xlsx,.xls" hidden></label></div><div class="between" style="margin-top:18px"><small>没有现成表格？可使用系统导入模板。</small><a href="/api/import-template" class="help-link">下载导入模板</a></div><p class="prototype-note">原表不会被修改。复杂图片公式和多图行需要导入后核对；旧版 .xls 图片请手动补充。</p>','<small id="importStatus">只在本机处理文件</small><button data-action="close">取消</button>');return}if(!importPreview)return;drawImportMapping()}
let importUploading=false;
async function uploadBook(file){
 if(!file||importUploading)return;
 if(!/\.(xlsx|xls)$/i.test(file.name))return toast('请选择 .xlsx 或 .xls 文件');
 if(file.size>500*1024*1024)return toast('Excel 文件超过 500 MB，请拆分后导入');
 importUploading=true;
 const status=$('#importStatus'),input=$('#bookInput'),zone=$('[data-import-dropzone]');
 if(input)input.disabled=true;if(zone)zone.setAttribute('aria-busy','true');
 if(status)status.textContent='正在本机读取 '+(file.size/1024/1024).toFixed(1)+' MB 表格，大文件需要一些时间…';
 try{
  const fd=new FormData();fd.append('file',file);
  const session=await api('/api/import/upload',{method:'POST',body:fd});
  session.config={sheet:session.sheets[0],header:1,prefix:'',start:1,factory:''};
  const preview=await api('/api/import/preview',{method:'POST',body:{batch:session.batch,...session.config}});
  if(!status?.isConnected)return;
  importSession=session;importPreview=preview;session.config.mapping=preview.mapping;drawImportMapping();
 }catch(e){if(status?.isConnected)status.textContent=e.message;toast(e.message)}
 finally{importUploading=false;if(input){input.disabled=false;input.value=''}if(zone)zone.removeAttribute('aria-busy')}
}

function importConfig(){const config={sheet:$('#importSheet').value,header:Number($('#importHeader').value),factory:$('#importFactory').value.trim(),prefix:$('#importPrefix').value.trim(),start:Number($('#importStart').value),mapping:{}};document.querySelectorAll('[data-import-field]').forEach(e=>{if(e.value!=='')config.mapping[e.dataset.importField]=Number(e.value)});return config}
function drawImportMapping(){
 const c=importSession.config,required=['code','factoryCode','name'];
 const orderedKeys=[...required,...Object.keys(importSession.fields).filter(key=>!required.includes(key))];
 const fields=orderedKeys.map(key=>{const label=importSession.fields[key];return '<label><span class="form-label">'+esc(label)+(required.includes(key)?' <em class="required-mark">*</em>':'')+'</span><select aria-label="'+esc(label)+'" data-import-field="'+key+'"><option value=""></option>'+importPreview.headers.map((h,i)=>'<option value="'+i+'" '+(c.mapping[key]===i?'selected':'')+'>'+(i+1)+' · '+esc(h||'空列名')+'</option>').join('')+'</select></label>'}).join('');
 openDialog('对应表格字段','文件：'+esc(importSession.filename),
 '<section class="import-section"><h3>数据读取</h3><div class="import-source-row"><label>工作表<select id="importSheet">'+importSession.sheets.map(s=>'<option '+(s===c.sheet?'selected':'')+'>'+esc(s)+'</option>').join('')+'</select></label><label>表头行<input id="importHeader" type="number" min="1" max="50" value="'+c.header+'"></label><button data-action="importReloadHeaders">重新读取表头</button></div></section>'+
 '<section class="import-section"><div class="import-section-heading"><h3>字段匹配</h3><small><em class="required-mark">*</em> 必填；销售编码、厂家名称可在下方补充</small></div><div class="import-mappings">'+fields+'</div></section>'+
 '<section class="import-section"><h3>信息补充</h3><div class="import-supplement"><label>统一厂家名称<input id="importFactory" value="'+esc(c.factory)+'" placeholder="原表缺少时补充"></label><label>销售编码前缀<input id="importPrefix" value="'+esc(c.prefix)+'" placeholder="例如 A" maxlength="12"></label><label>编码起始序号<input id="importStart" type="number" min="1" step="1" value="'+c.start+'"></label></div><p class="import-hint">仅补充原表空值。前缀 A、序号 1 → A-01、A-02…；已有编码保留，重复编码会提示。</p></section>',
 '<button data-action="import">重新选择文件</button><button class="primary" data-action="importValidate">校验并预览</button>');
}

async function reloadImportHeaders(){const button=$('[data-action="importReloadHeaders"]');button.disabled=true;try{const c=importConfig();delete c.mapping;importPreview=await api('/api/import/preview',{method:'POST',body:{batch:importSession.batch,...c}});importSession.config={...c,mapping:importPreview.mapping};drawImportMapping()}catch(e){toast(e.message)}finally{button.disabled=false}}
async function validateImport(){const button=$('[data-action="importValidate"]');button.disabled=true;try{importSession.config=importConfig();importPreview=await api('/api/import/preview',{method:'POST',body:{batch:importSession.batch,...importSession.config}});openDialog('核对后导入','仅提交校验通过的行；错误和重复行会跳过，不覆盖已有资料。','<div class="import-result"><b>共 '+importPreview.total+' 行 · 可导入 '+importPreview.valid+' 行 · 问题行 '+(importPreview.total-importPreview.valid)+' 行</b></div>'+importPreview.warnings.map(w=>'<div class="notice" style="margin:10px 0">'+esc(w)+'</div>').join('')+'<div class="table-scroll import-result-table"><table><thead><tr><th>原表行</th><th>销售编码</th><th>商品名称</th><th>厂家</th><th>装箱数</th><th>单价</th><th>校验结果</th></tr></thead><tbody>'+importPreview.rows.slice(0,100).map(r=>'<tr><td>'+r.row+'</td><td>'+esc(r.data.code)+'</td><td>'+esc(r.data.name)+'</td><td>'+esc(r.data.factory)+'</td><td>'+esc(r.data.pack)+'</td><td>'+esc(r.data.price)+'</td><td style="color:'+(r.error?'#c56745':'#338a69')+'">'+esc(r.error||'可导入')+'</td></tr>').join('')+'</tbody></table></div><p class="prototype-note">仅展示前 100 行，提交处理全部 '+importPreview.total+' 行。</p>','<button data-action="importNext">返回修改</button><button data-action="importErrors">下载问题行 CSV</button><button class="primary" data-action="importCommit" '+(!importPreview.valid?'disabled':'')+'>导入有效的 '+importPreview.valid+' 行</button>')}catch(e){toast(e.message)}finally{button.disabled=false}}
async function importCommit(){const button=$('[data-action="importCommit"]');button.disabled=true;try{const r=await api('/api/import/commit',{method:'POST',body:{batch:importSession.batch,previewId:importPreview.previewId}});closeDialog();query='';factory='';category='';await refreshProducts();toast('成功导入 '+r.count+' 款商品')}catch(e){toast(e.message);button.disabled=false}}
function importErrors(){const rows=importPreview.rows.filter(r=>r.error);if(!rows.length)return toast('没有问题行');const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const fields=Object.keys(importSession.fields);const data=[['原表行','问题',...Object.values(importSession.fields)],...rows.map(r=>[r.row,r.error,...fields.map(k=>r.data[k])])].map(r=>r.map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='导入问题行.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
async function backup(){try{const files=await api('/api/backups');openDialog('数据与备份','数据目录：'+esc(appState.dataDir),'<div class="between"><div><h3>备份数据库、图片和未完成清单</h3><p class="prototype-note">每天首次启动自动备份。可下载备份到其他设备，防止本机硬盘损坏。</p></div><button class="primary" data-action="backupCreate">立即备份</button></div><div class="table-scroll" style="margin-top:20px"><table><thead><tr><th>备份文件</th><th>大小</th><th>操作</th></tr></thead><tbody>'+files.map(f=>'<tr><td>'+esc(f.name)+'</td><td>'+(f.size/1024/1024).toFixed(2)+' MB</td><td><a href="/api/backups/'+encodeURIComponent(f.name)+'">下载</a>　<button data-action="backupRestore" data-name="'+esc(f.name)+'">恢复</button></td></tr>').join('')+'</tbody></table></div>','<small>恢复前会先自动备份当前资料。</small><button data-action="close">关闭</button>')}catch(e){toast(e.message)}}
async function createBackup(){const b=$('[data-action="backupCreate"]');b.disabled=true;try{await api('/api/backups',{method:'POST'});await backup();toast('备份已完成')}catch(e){toast(e.message);b.disabled=false}}
function restorePrompt(name){openDialog('恢复备份','将恢复数据库及对应图片，当前资料会先另存一份安全备份。','<p>备份：'+esc(name)+'</p><label class="stack" style="margin-top:18px">输入“恢复备份”确认<input id="restoreConfirm" autocomplete="off"></label>','<button data-action="backup">返回</button><button class="primary" data-action="backupRestoreConfirm" data-name="'+esc(name)+'">恢复备份</button>',true)}
async function restoreBackup(name){try{await api('/api/backups/restore',{method:'POST',body:{name,confirmation:$('#restoreConfirm').value}});appReady=false;closeDialog();await bootstrap();toast('资料已从备份恢复')}catch(e){toast(e.message)}}
async function history(){try{const rows=await api('/api/orders');openDialog('导出记录','保留最近 100 次生成记录；商品修改不会改变已生成报货单。','<div class="table-scroll"><table><thead><tr><th>开单时间</th><th>商品款数</th><th>件数</th><th>文件</th></tr></thead><tbody>'+rows.map(o=>'<tr><td>'+esc(o.createdAt.replace('T',' '))+'</td><td>'+o.items.length+'</td><td>'+o.items.reduce((n,p)=>n+p.quantity,0)+'</td><td><a href="/api/exports/'+encodeURIComponent(o.file)+'">下载报货单</a></td></tr>').join('')+'</tbody></table></div>'+(!rows.length?'<div class="empty">还没有生成过报货单。</div>':''))}catch(e){toast(e.message)}}
async function deletionHistory(){try{const rows=await api('/api/deletion-logs');openDialog('删除日志','记录商品资料的删除时间和当时的商品信息。','<div class="table-scroll deletion-history"><table><thead><tr><th>删除时间</th><th>销售编码</th><th>商品名称</th><th>厂家名称</th></tr></thead><tbody>'+rows.map(row=>'<tr><td>'+esc(row.deletedAt.replace('T',' '))+'</td><td class="mono">'+esc(row.code)+'</td><td>'+esc(row.name)+'</td><td>'+esc(row.factory||'—')+'</td></tr>').join('')+'</tbody></table></div>'+(!rows.length?'<div class="empty">还没有商品删除记录。</div>':''))}catch(e){toast(e.message)}}
function photoPage(){return '<div class="between page-title"><div><h1>图片开单</h1><p>识别在本机完成，不上传图片；手写内容请逐行核对。</p></div><span class="tag">'+(appState.ocrAvailable?'离线识别可用':'可手动录入')+'</span></div><div class="photo-steps"><div><span>1</span><b>上传订单图片</b><small>照片或聊天截图</small></div><i></i><div><span>2</span><b>核对识别结果</b><small>商品、数量、单位</small></div><i></i><div><span>3</span><b>确认并导出</b><small>按厂家生成报货单</small></div></div><section class="panel photo-main"><div class="between panel-head"><h3>订单图片</h3><small>JPG / PNG / WEBP · 单张不超过 15 MB</small></div><input type="file" id="orderPhotoInput" accept="image/jpeg,image/png,image/webp" hidden>'+(photoUrl?'<div class="photo-selected"><div class="between"><b>'+esc(photoName)+'</b><div class="flex"><button class="quiet" data-action="photoChoose">更换图片</button><button class="quiet" data-action="photoRemove">移除</button></div></div><div class="photo-preview" data-dropzone><img src="'+esc(photoUrl)+'" alt="订单原图" style="transform:rotate('+photoRotation+'deg)"></div><div class="between photo-tools"><small>建议先旋转到文字朝上，再开始识别。</small><button data-action="photoRotate">'+icon('refresh')+' 旋转 90°</button></div></div>':'<div class="photo-drop" data-dropzone tabindex="0" role="button" aria-label="选择或拖入订单图片" data-action="photoChoose"><div class="photo-upload-icon">'+icon('image')+'</div><h2>上传客户的订单图片</h2><p>拖入图片、点击选择文件，或直接粘贴截图</p><span class="primary-upload">'+icon('upload')+' 上传订单图片</span><small>拍正、拍清，保留商品编码和数量单位。</small></div>')+'<div class="photo-action"><div><b>先核对，再开单</b><p>潦草手写可能无法准确识别，可手动补充商品和数量。</p></div><div class="flex"><button data-action="photoManual" '+(!photoUrl?'disabled':'')+'>对照图片手动录入</button><button class="primary" data-action="photoRecognize" '+(!photoUrl||!appState.ocrAvailable?'disabled':'')+'>开始离线识别 '+icon('arrow')+'</button></div></div><div id="ocrStatus" class="photo-demo-note">仅识别你选择的这张图片，无付费调用。首次识别需要加载本机模型，可能稍慢。</div></section>'}
async function beginPhotoDemo(){if(!photoFile)return toast('请先上传订单图片');const button=$('[data-action="photoRecognize"]');button.disabled=true;$('#ocrStatus').textContent='正在本机识别，请稍候… 请勿关闭软件。';try{const fd=new FormData();fd.append('file',photoFile);const r=await api('/api/recognize?rotation='+photoRotation,{method:'POST',body:fd});ocrLines=r.lines;photoRows=r.rows.map(row=>({...row,key:++photoRowCounter}));if(!photoRows.length)photoRows=[{key:++photoRowCounter,raw:'未能可靠提取商品行，请对照原图手动补充。',id:0,quantity:0,unit:'',reviewed:false}];showPhotoConfirmation()}catch(e){toast('识别未完成：'+e.message);if($('#ocrStatus'))$('#ocrStatus').textContent='识别失败，可重试或对照图片手动录入。'}finally{button.disabled=false}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;if(a==='reload')bootstrap();else if(a==='history')history();else if(a==='deletionHistory')deletionHistory();else if(a==='changeDataDir')changeDataDir();else if(a==='dirOpen')openDataDirBrowser(b.dataset.path||'');else if(a==='dirUp')openDataDirBrowser(dirBrowserPath?dirBrowserPath.replace(/[\\/]?[^\\/]+[\\/]?$/,''):'');else if(a==='dirNew')createDataDirFolder();else if(a==='dataDirSelect')selectDataDir();else if(a==='importReloadHeaders')reloadImportHeaders();else if(a==='importErrors')importErrors();else if(a==='backupCreate')createBackup();else if(a==='backupRestore')restorePrompt(b.dataset.name);else if(a==='backupRestoreConfirm')restoreBackup(b.dataset.name);else if(a==='photoManual'){ocrLines=[];photoRows=[{key:++photoRowCounter,raw:'手动录入',id:0,quantity:1,unit:'',reviewed:false}];showPhotoConfirmation()}else if(a==='shutdown'){openDialog('退出系统','退出前会保存当前待开单清单。','<p>关闭浏览器标签页不会停止本地服务。点击下方按钮退出软件。</p>','<button data-action="close">取消</button><button class="primary" data-action="shutdownConfirm">保存并退出</button>',true)}else if(a==='shutdownConfirm'){persistDraft().then(async()=>{if(draftError)return;await api('/api/shutdown',{method:'POST'});closeDialog();appReady=false;$('#app').innerHTML='<div class="connection-error"><h2>系统已退出</h2><p>资料已保存在本机，可以关闭此页面。</p></div>'}).catch(e=>toast(e.message))}});
document.addEventListener('change',e=>{if(e.target.id==='bookInput')uploadBook(e.target.files[0])});
document.addEventListener('input',e=>{if(e.target.dataset.qty)persistDraft()});
window.addEventListener('pagehide',()=>{if(appReady&&JSON.stringify(draftData())!==draftLastSaved)fetch('/api/draft',{method:'PUT',keepalive:true,headers:{'Content-Type':'application/json','X-Counter-Request':'1'},body:JSON.stringify(draftData())}).catch(()=>{})});
const legacyRender=render;
render=function(){legacyRender();document.querySelector('.batch-example')?.remove();const helper=document.querySelector('.library-helper');if(helper){const label=helper.querySelector('label');const target=document.querySelector('.panel-head .flex:last-child');if(label&&target)target.insertBefore(label,target.firstChild);helper.remove()}};

document.addEventListener('dragover',e=>{const zone=e.target.closest('[data-import-dropzone]');if(!zone)return;e.preventDefault();e.dataTransfer.dropEffect=importUploading?'none':'copy';zone.classList.add('dragging')});
document.addEventListener('dragleave',e=>{const zone=e.target.closest('[data-import-dropzone]');if(zone&&!zone.contains(e.relatedTarget))zone.classList.remove('dragging')});
document.addEventListener('drop',e=>{const zone=e.target.closest('[data-import-dropzone]');if(!zone)return;e.preventDefault();zone.classList.remove('dragging');if(e.dataTransfer.files.length!==1)return toast('请每次导入一个 Excel 文件');uploadBook(e.dataTransfer.files[0])});

// 正式版本统一交付安装程序；重复安装会覆盖固定程序目录并保留独立数据目录。
async function showUpdate(){openDialog('检查软件更新','正在连接 GitHub Releases…','<div class="update-intro"><div class="update-mark">'+icon('refresh')+'</div><h2>正在检查最新版本</h2><p>只读取公开版本信息，不会上传商品资料。</p></div>','<small>当前版本 '+version+'</small><button class="primary" data-action="close">取消</button>',true);try{const info=await api('/api/update/check');if(info.status==='ok'&&info.updateAvailable){const size=info.package?.bytes?((info.package.bytes/1024/1024).toFixed(1)+' MB'):'大小未知';openDialog('发现新版本','当前版本 '+esc(info.currentVersion)+' · 最新版本 '+esc(info.latestVersion),'<div class="update-intro"><div class="update-mark">'+icon('refresh')+'</div><h2>'+esc(info.releaseName||('版本 '+info.latestVersion))+'</h2><p>安装程序约 '+size+'，发布于 '+esc((info.publishedAt||'').slice(0,10)||'未知日期')+'</p></div><div class="update-notes">'+(info.notes?esc(info.notes).replace(/\r?\n/g,'<br>'):'本次更新暂无说明')+'</div><p class="prototype-note">下载完成后先退出当前软件，再运行安装程序。它会覆盖同一程序目录并更新桌面图标，商品资料、图片和数据目录会保留。</p>','<small>来源：GitHub Releases</small><a class="primary" href="'+esc(info.package.url)+'" target="_blank" rel="noreferrer">下载安装程序</a>',true)}else if(info.status==='no-release'){openDialog('软件版本与维护','当前版本 '+version+' · GitHub Releases','<div class="update-intro"><div class="update-mark">'+icon('check')+'</div><h2>暂未发布在线更新</h2><p>当前版本已经是本机可用版本。</p></div><div class="update-notes">发布新版本后，这里会显示版本号、更新说明和安装程序下载入口。</div>','<small>更新源已配置</small><button class="primary" data-action="close">知道了</button>',true)}else{openDialog('软件版本与维护','当前版本 '+version+' · GitHub Releases','<div class="update-intro"><div class="update-mark">'+icon('refresh')+'</div><h2>暂时无法完成检查</h2><p>'+esc(info.message||'更新服务暂时不可用')+'</p></div><div class="update-notes">请稍后重试。商品资料和图片不会受到影响。</div>','<small>更新源：GitHub Releases</small><button class="primary" data-action="close">知道了</button>',true)}}catch(e){openDialog('软件版本与维护','当前版本 '+version,'<div class="update-intro"><div class="update-mark">'+icon('refresh')+'</div><h2>暂时无法完成检查</h2><p>'+esc(e.message)+'</p></div><div class="update-notes">请稍后重试。商品资料和图片不会受到影响。</div>','<small>更新源：GitHub Releases</small><button class="primary" data-action="close">知道了</button>',true)}}
if(new URLSearchParams(location.search).get('updated')==='1')setTimeout(()=>{if(typeof toast==='function'&&version)toast('更新完成，已启动新版本 v'+version)},1800);

let mediaDraft={images:[],boxImages:[]},mediaBusy=false,mediaGeneration=0;
const mediaLabels={images:'主图',boxImages:'彩盒'};
function mediaGroup(key){
 const list=mediaDraft[key];
 return '<section class="media-group" data-media-drop="'+key+'"><div class="between"><b>'+mediaLabels[key]+'</b><small>'+list.length+' / 5</small></div><div class="media-tiles">'+list.map((name,i)=>'<div class="media-tile"><img src="/api/images/'+name+'" alt="'+mediaLabels[key]+' '+(i+1)+'"><button type="button" class="image-remove" data-media-remove="'+key+'" data-index="'+i+'" aria-label="删除'+mediaLabels[key]+'第'+(i+1)+'张" '+(mediaBusy?'disabled':'')+'>×</button></div>').join('')+(list.length<5?'<button type="button" class="media-add" data-media-add="'+key+'" aria-label="添加'+mediaLabels[key]+'" '+(mediaBusy?'disabled':'')+'><span>+</span><small>添加图片</small></button>':'')+'</div><input type="file" id="mediaInput-'+key+'" data-media-input="'+key+'" accept="image/jpeg,image/png,image/webp" multiple hidden><small class="media-note">'+(mediaBusy?'正在上传，请稍候…':'可拖入多张图片 · 每张最多 15 MB')+'</small></section>';
}
function renderMedia(){const area=$('#productMedia');if(area)area.innerHTML=Object.keys(mediaLabels).map(mediaGroup).join('')}
const productFields=[['code','销售编码',true],['factoryCode','厂家编码',true],['name','商品名称',true],['factory','厂家名称',false],['color','颜色',false],['size','尺寸',false],['cartonSize','外箱尺寸',false],['cartonWeight','单箱重量（kg）',false],['material','材质',false],['pack','装箱数（个 / 件）',false],['price','出厂价（元 / 个）',false],['battery','电池容量',false],['charger','充电头 / 接口',false],['volume','单件体积（m³）',false],['cat','商品分类',false],['parameters','产品参数',false],['notes','备注',false]];
const productFieldMap=Object.fromEntries(productFields.map(field=>[field[0],field]));
function productFieldKeys(){const saved=appState?.productFieldOrder||[];return [...saved.filter(key=>productFieldMap[key]),...productFields.map(field=>field[0]).filter(key=>!saved.includes(key))]}
function productVisibleKeys(){const saved=appState?.productFieldVisible||[];return new Set(saved.length?saved:productFields.map(field=>field[0]))}
function productFieldInput(key,p){
 const [_,label,required]=productFieldMap[key];
 const value=esc(p[key]??'');
 const input=key==='parameters'||key==='notes'?'<textarea name="'+key+'" maxlength="'+(key==='parameters'?'3000':'300')+'">'+value+'</textarea>':'<input name="'+key+'" value="'+value+'" '+(key==='pack'?'type="number" min="0" max="1000000" step="1"':key==='price'?'type="number" min="0" max="100000000" step="0.01"':key==='volume'?'type="number" min="0" max="100000000" step="0.000001"':key==='cartonWeight'?'type="number" min="0" max="100000" step="0.001"':'maxlength="300"')+(required?' required':'')+'>';
 return '<div class="product-field-card" data-product-field="'+key+'"><label><span class="form-label">'+label+(required?' <em class="required-mark">*</em>':'')+'</span>'+input+'</label></div>';
}
function syncProductFieldGrid(){const grid=$('#productFieldGrid');if(!grid)return;const visible=productVisibleKeys();for(const key of productFieldKeys()){const card=grid.querySelector('[data-product-field="'+key+'"]');if(card){grid.append(card);card.hidden=!visible.has(key)}}}
let productFieldDraft=null,productFieldDragKey='';
function drawProductFieldConfig(){const list=$('#productFieldConfigList');if(!list||!productFieldDraft)return;list.innerHTML=productFieldDraft.order.map(key=>{const [_,label,required]=productFieldMap[key];return '<div class="product-config-row" data-product-config-key="'+key+'"><label><input type="checkbox" data-product-config-check="'+key+'" '+(productFieldDraft.visible.has(key)?'checked':'')+' '+(required?'disabled':'')+'><span>'+label+(required?' <em class="required-mark">*</em>':'')+'</span></label><span class="product-config-grip" draggable="true" data-product-config-drag="'+key+'" aria-label="拖动调整'+label+'位置" title="拖动调整'+label+'位置">☰</span></div>'}).join('')}
function openProductFieldConfig(){productFieldDraft={order:productFieldKeys(),visible:productVisibleKeys()};$('#dialog').insertAdjacentHTML('beforeend','<div class="product-config-backdrop" id="productFieldConfig" role="dialog" aria-modal="true" aria-label="字段配置"><section class="product-config-panel"><header><b>字段配置</b><button type="button" data-product-config="cancel" aria-label="关闭字段配置">×</button></header><p>勾选显示字段，拖动右侧图标调整顺序。</p><div class="product-config-list" id="productFieldConfigList"></div><footer><button type="button" data-product-config="cancel">取消</button><button type="button" data-product-config="reset">恢复默认</button><button type="button" class="primary" data-product-config="save">确定</button></footer></section></div>');drawProductFieldConfig();$('[data-product-config="cancel"]').focus()}
function closeProductFieldConfig(){document.querySelector('#productFieldConfig')?.remove();productFieldDraft=null;productFieldDragKey='';$('[data-action="productFieldConfig"]')?.focus()}
async function saveProductFieldConfig(){if(!productFieldDraft)return;const button=$('[data-product-config="save"]');button.disabled=true;const order=[...productFieldDraft.order],visible=order.filter(key=>productFieldDraft.visible.has(key));try{const saved=await api('/api/product-field-order',{method:'PUT',body:{order,visible}});appState.productFieldOrder=saved.order;appState.productFieldVisible=saved.visible;syncProductFieldGrid();closeProductFieldConfig();toast('字段配置已保存')}catch(e){button.disabled=false;toast(e.message)}}
async function uploadMedia(key,files){
 if(mediaBusy)return toast('请等待当前图片上传完成');
 const list=Array.from(files||[]);if(!list.length)return;
 if(list.length+mediaDraft[key].length>5)return toast(mediaLabels[key]+'最多上传 5 张，请减少选择的图片');
 if(list.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>15*1024*1024))return toast('请上传 JPG、PNG、WEBP，每张不超过 15 MB');
 const generation=mediaGeneration,target=mediaDraft[key];mediaBusy=true;renderMedia();
 const save=$('[form="productForm"]');if(save)save.disabled=true;
 try{for(const file of list){const fd=new FormData();fd.append('file',file);const r=await api('/api/images',{method:'POST',body:fd});if(generation!==mediaGeneration)return;target.push(r.image)}}
 catch(e){toast(e.message)}finally{mediaBusy=false;if(generation===mediaGeneration){renderMedia();if(save)save.disabled=false}}
}
function newForm(id){
 if(mediaBusy)return toast('图片正在上传，请稍候');
 const p=products.find(p=>p.id===id)||{cat:'日用百货',volume:0};mediaGeneration++;
 mediaDraft={images:[...(p.images||(p.image?[p.image]:[]))],boxImages:[...(p.boxImages||[])]};
 openDialog(id?'编辑商品资料':'新增商品','保存后写入本机数据库。','<form id="productForm" data-id="'+(id||'')+'"><div id="productMedia" class="product-media">'+Object.keys(mediaLabels).map(mediaGroup).join('')+'</div><div class="product-fields-heading"><b>商品信息</b><button type="button" data-action="productFieldConfig">⚙ 字段配置</button></div><div id="productFieldGrid" class="form-grid product-field-grid">'+productFieldKeys().map(key=>productFieldInput(key,p)).join('')+'</div></form>','<small>销售编码唯一；厂家编码在同一厂家内唯一。</small><button class="primary" type="submit" form="productForm">保存商品</button>');
 syncProductFieldGrid();
}
async function saveProduct(form){
 if(mediaBusy)return toast('请等待图片上传完成');if(!form.reportValidity())return;
 const button=$('[form="productForm"]');button.disabled=true;
 try{const data=Object.fromEntries(new FormData(form)),id=Number(form.dataset.id);data.images=[...mediaDraft.images];data.boxImages=[...mediaDraft.boxImages];for(const key of ['pack','price','volume'])data[key]=Number(data[key]||0);if(data.cartonWeight!=='')data.cartonWeight=Number(data.cartonWeight);await api(id?'/api/products/'+id:'/api/products',{method:id?'PUT':'POST',body:data});closeDialog();await refreshProducts();toast('商品资料已保存到本机')}
 catch(e){toast(e.message)}finally{button.disabled=false}
}
function detail(id){
 const p=products.find(x=>x.id===id);if(!p)return;
 const galleries=Object.entries(mediaLabels).map(([key,label])=>{const list=p[key]||(key==='images'&&p.image?[p.image]:[]);return '<section class="detail-gallery"><b>'+label+'</b><div class="detail-images">'+(list.length?list.map((name,i)=>'<a href="/api/images/'+name+'" target="_blank" rel="noreferrer"><img src="/api/images/'+name+'" alt="'+label+' '+(i+1)+'"></a>').join(''):'<div class="media-empty">暂无'+label+'</div>')+'</div></section>'}).join('');
 const detailValue=key=>key==='pack'?p.pack+' 个 / 件':key==='cartonWeight'&&p.cartonWeight!==''?p.cartonWeight+' kg':key==='volume'?p.volume+' m³':p[key];
 const visible=productVisibleKeys();
 openDialog('商品资料','编码、规格与厂家信息','<div class="between"><div><span class="tag">'+esc(p.cat)+'</span><h2>'+esc(p.name)+'</h2></div><div><small>出厂价 / 个</small><div style="font-size:27px">'+money(p.price)+'</div></div></div><div class="product-media detail-media">'+galleries+'</div><div class="section-label">商品资料</div><div class="fields product-detail-fields">'+productFieldKeys().filter(key=>visible.has(key)).map(key=>{const value=detailValue(key);return '<div class="field" data-detail-field="'+key+'"><small>'+productFieldMap[key][1]+'</small><b>'+esc(value===''||value==null?'—':value)+'</b></div>'}).join('')+'</div>','<button class="danger" data-action="productDelete" data-id="'+id+'">删除商品</button><button data-action="edit" data-id="'+id+'">修改资料</button><button class="primary" data-action="detailPick" data-id="'+id+'">'+(selected.has(id)?'从待开单移除':'加入待开单')+'</button>');
}
function promptProductDelete(id){
 const p=products.find(x=>x.id===id);if(!p)return toast('商品已不存在');
 openDialog('删除商品资料','确认后会从商品库和当前待开单清单移除。历史报价单保留。','<p>确定删除 <b>'+esc(p.code)+' · '+esc(p.name)+'</b> 吗？</p>','<button data-action="close">取消</button><button class="danger" data-action="productDeleteConfirm" data-id="'+id+'">确认删除</button>',true);
}
async function confirmProductDelete(id){
 const p=products.find(x=>x.id===id);if(!p)return toast('商品已不存在');
 const button=$('[data-action="productDeleteConfirm"]');button.disabled=true;
 try{await api('/api/products/'+id,{method:'DELETE'});selected.delete(id);delete quantities[id];closeDialog();await refreshProducts();toast('商品已删除，历史报价单保留')}
 catch(e){toast(e.message);button.disabled=false}
}
let pendingBulkDeleteIds=[];
function promptBulkProductDelete(){
 pendingBulkDeleteIds=[...selected];
 const rows=products.filter(p=>pendingBulkDeleteIds.includes(p.id));
 if(!rows.length)return toast('请先勾选要删除的商品');
 const names=rows.slice(0,5).map(p=>'<li>'+esc(p.code)+' · '+esc(p.name)+'</li>').join('');
 openDialog('批量删除商品','确认后删除已勾选商品，历史报价单保留。','<p>将删除 <b>'+rows.length+' 款商品</b>，并从当前待开单清单移除。</p><ul class="delete-product-list">'+names+'</ul>'+(rows.length>5?'<small>另外还有 '+(rows.length-5)+' 款已选商品</small>':''),'<button data-action="close">取消</button><button class="danger" data-action="productsBulkDeleteConfirm">确认删除 '+rows.length+' 款</button>',true);
}
async function confirmBulkProductDelete(){
 const button=$('[data-action="productsBulkDeleteConfirm"]');button.disabled=true;
 const ids=[...pendingBulkDeleteIds];
 try{const result=await api('/api/products/bulk-delete',{method:'POST',body:{ids}});for(const id of ids){selected.delete(id);delete quantities[id]}pendingBulkDeleteIds=[];closeDialog();await refreshProducts();toast('已删除 '+result.count+' 款商品，历史报价单保留')}
 catch(e){toast(e.message);button.disabled=false}
}
document.addEventListener('click',e=>{const button=e.target.closest('[data-action="productDelete"],[data-action="productDeleteConfirm"],[data-action="productsBulkDelete"],[data-action="productsBulkDeleteConfirm"]');if(!button||button.disabled)return;const id=Number(button.dataset.id),action=button.dataset.action;if(action==='productDelete')promptProductDelete(id);else if(action==='productDeleteConfirm')confirmProductDelete(id);else if(action==='productsBulkDelete')promptBulkProductDelete();else confirmBulkProductDelete()});
document.addEventListener('click',e=>{const add=e.target.closest('[data-media-add]'),remove=e.target.closest('[data-media-remove]');if(add&&!add.disabled)$('#mediaInput-'+add.dataset.mediaAdd)?.click();if(remove&&!mediaBusy){mediaDraft[remove.dataset.mediaRemove].splice(Number(remove.dataset.index),1);renderMedia()}});
document.addEventListener('change',e=>{if(e.target.dataset.mediaInput)uploadMedia(e.target.dataset.mediaInput,e.target.files)});
document.addEventListener('dragover',e=>{const zone=e.target.closest('[data-media-drop]');if(zone){e.preventDefault();zone.classList.add('dragging')}});
document.addEventListener('dragleave',e=>{const zone=e.target.closest('[data-media-drop]');if(zone&&!zone.contains(e.relatedTarget))zone.classList.remove('dragging')});
document.addEventListener('drop',e=>{const zone=e.target.closest('[data-media-drop]');if(zone){e.preventDefault();zone.classList.remove('dragging');uploadMedia(zone.dataset.mediaDrop,e.dataTransfer.files)}});
document.addEventListener('click',e=>{if(e.target.closest('[data-action="productFieldConfig"]'))openProductFieldConfig();const button=e.target.closest('[data-product-config]');if(button){if(button.dataset.productConfig==='cancel')closeProductFieldConfig();else if(button.dataset.productConfig==='reset'){productFieldDraft={order:productFields.map(field=>field[0]),visible:new Set(productFields.map(field=>field[0]))};drawProductFieldConfig()}else if(button.dataset.productConfig==='save')saveProductFieldConfig()}if(e.target.id==='productFieldConfig')closeProductFieldConfig()});
document.addEventListener('change',e=>{const key=e.target.dataset.productConfigCheck;if(!key||!productFieldDraft)return;e.target.checked?productFieldDraft.visible.add(key):productFieldDraft.visible.delete(key)});
document.addEventListener('dragstart',e=>{const grip=e.target.closest('[data-product-config-drag]');if(!grip)return;productFieldDragKey=grip.dataset.productConfigDrag;e.dataTransfer.setData('text/plain',productFieldDragKey);e.dataTransfer.effectAllowed='move';grip.closest('[data-product-config-key]').classList.add('dragging')});
document.addEventListener('dragover',e=>{if(productFieldDragKey&&e.target.closest('[data-product-config-key]')){e.preventDefault();e.dataTransfer.dropEffect='move'}});
document.addEventListener('drop',e=>{const row=e.target.closest('[data-product-config-key]');if(!row||!productFieldDragKey||!productFieldDraft)return;e.preventDefault();const keys=productFieldDraft.order,from=keys.indexOf(productFieldDragKey),to=keys.indexOf(row.dataset.productConfigKey);if(from>=0&&to>=0&&from!==to){keys.splice(to,0,keys.splice(from,1)[0]);drawProductFieldConfig()}productFieldDragKey=''});
document.addEventListener('dragend',()=>{productFieldDragKey='';document.querySelectorAll('.product-config-row.dragging').forEach(node=>node.classList.remove('dragging'))});
$('#dialog').addEventListener('cancel',e=>{if($('#productFieldConfig')){e.preventDefault();closeProductFieldConfig()}});

let exportOrderKeys=[],exportChecked=new Set(),exportDragKey='';
function selectedExportColumns(){return exportOrderKeys.filter(k=>exportChecked.has(k))}
function drawExportFields(){
 const area=$('#exportFields');if(!area)return;
 area.innerHTML=exportOrderKeys.map((key,i)=>'<div class="export-field" draggable="true" data-export-key="'+key+'"><span class="export-grip" aria-hidden="true">⠿</span><label><input type="checkbox" data-export-check="'+key+'" '+(exportChecked.has(key)?'checked':'')+'>'+esc(appState.exportFields[key])+'</label><button type="button" data-export-move="'+key+'" data-step="-1" aria-label="上移'+esc(appState.exportFields[key])+'" '+(i===0?'disabled':'')+'>↑</button><button type="button" data-export-move="'+key+'" data-step="1" aria-label="下移'+esc(appState.exportFields[key])+'" '+(i===exportOrderKeys.length-1?'disabled':'')+'>↓</button></div>').join('');
 $('#exportFieldCount').textContent='已选 '+exportChecked.size+' 项';
}
const baseOrder=order;
order=function(){
 if(!selected.size)return baseOrder();baseOrder();
 const all=Object.keys(appState.exportFields),saved=(appState.exportColumns||all).filter(k=>all.includes(k));
 exportOrderKeys=[...saved,...all.filter(k=>!saved.includes(k))];exportChecked=new Set(saved);
 $('#orderTotals').insertAdjacentHTML('afterend','<details class="export-config"><summary>导出字段与顺序 <small id="exportFieldCount"></small></summary><p>勾选需要的字段，拖动或点击箭头调整顺序。</p><div id="exportFields"></div><button type="button" data-action="saveExportFields">保存字段配置</button></details>');drawExportFields();
};
document.addEventListener('change',e=>{const key=e.target.dataset.exportCheck;if(!key)return;e.target.checked?exportChecked.add(key):exportChecked.delete(key);$('#exportFieldCount').textContent='已选 '+exportChecked.size+' 项'});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-export-move]');if(b&&!b.disabled){const i=exportOrderKeys.indexOf(b.dataset.exportMove),j=i+Number(b.dataset.step);[exportOrderKeys[i],exportOrderKeys[j]]=[exportOrderKeys[j],exportOrderKeys[i]];drawExportFields()}const save=e.target.closest('[data-action="saveExportFields"]');if(save){save.disabled=true;try{const r=await api('/api/export-settings',{method:'PUT',body:{columns:selectedExportColumns()}});appState.exportColumns=r.columns;toast('导出字段与顺序已保存')}catch(err){toast(err.message)}finally{save.disabled=false}}});
document.addEventListener('dragstart',e=>{const row=e.target.closest('[data-export-key]');if(row){exportDragKey=row.dataset.exportKey;e.dataTransfer.setData('text/plain',exportDragKey);e.dataTransfer.effectAllowed='move'}});
document.addEventListener('dragover',e=>{if(exportDragKey&&e.target.closest('[data-export-key]')){e.preventDefault();e.dataTransfer.dropEffect='move'}});
document.addEventListener('drop',e=>{const row=e.target.closest('[data-export-key]');if(!row||!exportDragKey)return;e.preventDefault();const from=exportOrderKeys.indexOf(exportDragKey),to=exportOrderKeys.indexOf(row.dataset.exportKey);if(from>=0&&to>=0){exportOrderKeys.splice(to,0,exportOrderKeys.splice(from,1)[0]);drawExportFields()}exportDragKey=''});
document.addEventListener('dragend',()=>{exportDragKey=''});

// Remove the prototype-only helper copy and batch-query prompt from the
// production page. The base template still contains the legacy markup because
// it is also used by the design prototype.
const productionRender=render;
render=function(){productionRender();document.querySelector('.batch-example')?.remove();document.querySelector('.library-helper')?.remove();const orderButton=document.querySelector('.selectedbar [data-action="order"]');if(orderButton){const actions=document.createElement('div'),deleteButton=document.createElement('button');actions.className='selection-actions';deleteButton.className='danger';deleteButton.dataset.action='productsBulkDelete';deleteButton.textContent='批量删除';deleteButton.disabled=!selected.size;deleteButton.title='删除已勾选商品';orderButton.replaceWith(actions);actions.append(deleteButton,orderButton)}};

// Keep the empty supplier state concise: the page title is enough when no
// supplier has been maintained yet.
suppliers=function(){const supplierNames=[...new Set(products.map(p=>p.factory).filter(Boolean))];if(!supplierNames.length){openDialog('合作厂家','','<div class="empty"><h3>暂无厂家</h3></div>');return}openDialog('合作厂家','选择厂家后查看对应商品','<div class="stack">'+supplierNames.map(f=>{let ps=products.filter(p=>p.factory===f);return '<div class="panel" style="padding:18px"><div class="between"><div><h3>'+esc(f)+'</h3><small>'+ps.length+' 款商品</small></div><button data-action="filterFactory" data-factory="'+esc(f)+'">查看商品</button></div></div>'}).join('')+'</div>')};

bootstrap();
