
'use strict';
const paths={image:'M3 3h18v18H3ZM3 17l6-6 4 4 3-3 5 5M8 7h.01',search:'M21 21l-5-5M10.5 18a7.5 7.5 0 1 0 0-15 7.5 7.5 0 0 0 0 15',box:'m3 7 9-5 9 5v10l-9 5-9-5ZM3 7l9 5 9-5M12 12v10M7 4.8l10 5.5',grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',file:'M14 2H5v20h14V7ZM14 2v6h5M8 13h8M8 17h8',upload:'M12 16V3m-5 5 5-5 5 5M3 15v6h18v-6',plus:'M12 4v16M4 12h16',refresh:'M20 8a8 8 0 0 0-14-3L3 8m0-5v5h5M4 16a8 8 0 0 0 14 3l3-3m0 5v-5h-5',shield:'m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6ZM8 12l3 3 5-6',factory:'M3 21V9l6 4V7l6 4V3h6v18ZM6 17h2m3 0h2m3 0h2',check:'m5 12 4 4L20 5',arrow:'M4 12h16m-6-6 6 6-6 6',clock:'M12 8v5l4 2M22 12a10 10 0 1 0-20 0 10 10 0 0 0 20 0',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2'};
function icon(n){return '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="'+(paths[n]||paths.box)+'"/></svg>'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
let products=[],selected=new Set(),viewMode='list',theme='a',query='',factory='',category='',quantities={},mode='single',version='1.0.0',updateTimer=null,toastTimer=null,importStep=1,importDone=false,lastFocus=null;
const $=s=>document.querySelector(s),money=n=>'¥'+Number(n).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
function art(p){return p.image?'<img class="real-product-image" src="/api/images/'+esc(p.image)+'" alt="'+esc(p.name)+'">':'<div class="no-product-image">'+icon('image')+'<small>暂无图片</small></div>'}
function thumb(p){return '<div class="thumb" style="background:'+(p.color||'#f3f6fa')+'">'+art(p)+'</div>'}
function toast(s){$('#toast').textContent=s;$('#toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),3400)}
function picked(){return products.filter(p=>selected.has(p.id))}
function tokens(){return query.trim().toUpperCase().split(/[\s,，;；、]+/).filter(Boolean)}
function result(){let t=tokens();return products.filter(p=>(!factory||p.factory===factory)&&(!category||p.cat===category)&&(!t.length||(t.length>1?t.includes(p.code.toUpperCase()):[p.code,p.name,p.factoryCode,p.factory].some(x=>x.toUpperCase().includes(t[0])))))}
function missing(){let t=tokens();return t.length>1?t.filter(x=>!products.some(p=>p.code.toUpperCase()===x)):[]}
function factoryOptions(){return '<option value="">全部厂家</option>'+[...new Set(products.map(p=>p.factory))].map(f=>'<option '+(factory===f?'selected':'')+'>'+esc(f)+'</option>').join('')}
function logo(){return '<div class="brand"><span class="brand-mark">货</span><div><div class="brand-name">货有数</div><div class="brand-sub">档口开单系统</div></div></div>'}
function side(){return '<aside class="sidebar">'+logo()+'<div class="nav-group"><nav class="nav"><button class="'+(activePage==='products'?'active':'')+'" data-action="all">'+icon('grid')+'<span class="nav-text">商品资料</span></button><button class="'+(activePage==='photo'?'active':'')+'" data-action="photo">'+icon('image')+'<span class="nav-text">图片开单</span></button><button data-action="suppliers">'+icon('factory')+'<span class="nav-text">厂家信息</span></button></nav></div><div class="sidebar-bottom"><button class="quiet" data-action="history">'+icon('clock')+' 导出记录</button><span id="saveState"><i class="dot"></i> 数据存储在本机</span><button class="quiet" data-action="backup">'+icon('shield')+' 数据与备份</button><button class="quiet" data-action="update">'+icon('refresh')+' 检查更新 <small>v'+version+'</small></button></div></aside>'}
function title(){return '<div class="between page-title library-title"><h1>商品资料库</h1><div class="flex"><button data-action="import">'+icon('upload')+' Excel 导入</button><button class="primary" data-action="new">'+icon('plus')+' 新增商品</button></div></div>'}
function stats(){let items=[['在售商品',products.length,'款','box'],['合作厂家',new Set(products.map(p=>p.factory)).size,'家','factory'],['销售编码覆盖','100','%','check']];return '<div class="stats">'+items.map(a=>'<div class="stat"><div><small>'+a[0]+'</small><b>'+a[1]+' <small>'+a[2]+'</small></b></div><span class="stat-icon">'+icon(a[3])+'</span></div>').join('')+'</div>'}
function searchbar(){return '<div class="searchbar"><div class="searchfield">'+icon('search')+'<input id="search" aria-label="搜索商品" placeholder="搜索销售编码、商品名称，多个编码用空格或逗号分隔" value="'+esc(query)+'"></div><button class="primary" data-action="search">查询</button><select id="factory" aria-label="厂家筛选">'+factoryOptions()+'</select><button data-action="reset" title="清空筛选">重置</button></div>'}
function missingHtml(){let m=missing();return m.length?'<div class="notice">有 '+m.length+' 个销售编码未找到：<b>'+m.map(esc).join('、')+'</b>。请核对编码后重新查询。</div>':''}
function table(){let rows=result();return '<div class="panel"><div class="between panel-head"><div class="flex"><h3>商品资料</h3><span class="tag">'+products.length+' 款</span></div><div class="flex"><button class="help-link batch-example" data-action="example">试试批量查询 →</button><div class="view-switch" role="group" aria-label="商品显示模式"><button data-action="viewMode" data-view="list" aria-pressed="'+(viewMode==='list')+'" class="'+(viewMode==='list'?'active':'')+'">'+icon('file')+' 列表</button><button data-action="viewMode" data-view="grid" aria-pressed="'+(viewMode==='grid')+'" class="'+(viewMode==='grid'?'active':'')+'">'+icon('grid')+' 大图</button></div></div></div>'+searchbar()+missingHtml()+'<div class="library-helper between"><span>支持多个销售编码同时查询 · 切换筛选或显示模式，已选商品仍保留</span>'+(viewMode==='grid'?'<label class="flex"><input type="checkbox" id="selectAll" aria-label="选择当前结果" '+(rows.length&&rows.every(p=>selected.has(p.id))?'checked':'')+'>选择当前结果</label>':'')+'</div>'+(viewMode==='list'?'<div class="table-scroll"><table><thead><tr><th><input type="checkbox" id="selectAll" aria-label="选择当前结果" '+(rows.length&&rows.every(p=>selected.has(p.id))?'checked':'')+'></th><th>销售编码</th><th>商品 / 规格</th><th>厂家编码</th><th>供货厂家</th><th>装箱数</th><th>出厂价 / 个</th><th>操作</th></tr></thead><tbody>'+rows.map(p=>'<tr class="'+(selected.has(p.id)?'selected':'')+'"><td><input type="checkbox" data-select="'+p.id+'" aria-label="选择 '+esc(p.code)+'" '+(selected.has(p.id)?'checked':'')+'></td><td><b class="mono code">'+esc(p.code)+'</b></td><td><div class="product-cell">'+thumb(p)+'<div><strong>'+esc(p.name)+'</strong><small>'+esc(p.size)+'</small></div></div></td><td class="mono" style="color:#8c96a5">'+esc(p.factoryCode)+'</td><td>'+esc(p.factory)+'<br><small>'+esc(p.area)+'</small></td><td>'+p.pack+' <small>个 / 件</small></td><td class="price">'+money(p.price)+'</td><td><button class="quiet help-link" data-action="detail" data-id="'+p.id+'">详情</button></td></tr>').join('')+'</tbody></table></div>':cardGrid(rows))+(!rows.length?empty():'')+'<div class="table-footer"><span>当前 '+rows.length+' 款 / 全部 '+products.length+' 款</span><span>本次已选 '+selected.size+' 款</span></div></div>'}
function empty(){return '<div class="empty">'+icon('search')+'<h3>没有找到匹配商品</h3><p>检查销售编码，或清空厂家筛选后再试试。</p><button style="margin-top:15px" data-action="reset">清空筛选</button></div>'}
function selectedbar(){return '<div class="selectedbar"><div class="flex"><span class="selection-count">'+selected.size+'</span><div><b>'+(selected.size?'款商品待开单':'还没有选择商品')+'</b><br><small>'+(selected.size?'来自 '+new Set(picked().map(p=>p.factory)).size+' 家厂家 · 同一商品只计 1 款':'勾选商品后，可统一填写件数并生成报货单')+'</small></div>'+(selected.size?'<button class="quiet" data-action="pending">查看清单</button><button class="quiet" data-action="clear">清空</button>':'')+'</div><button class="primary" data-action="order" '+(!selected.size?'disabled':'')+'>开报货单 '+icon('arrow')+'</button></div>'}
function cardGrid(rows){return '<div class="catalog-grid library-grid">'+rows.map(p=>'<article class="product-card '+(selected.has(p.id)?'chosen':'')+'"><label class="card-check"><input type="checkbox" data-select="'+p.id+'" aria-label="选择 '+esc(p.code)+'" '+(selected.has(p.id)?'checked':'')+'></label><div class="card-visual" style="background:'+(p.color||'#f3f6fa')+'" data-action="detail" data-id="'+p.id+'" tabindex="0" role="button" aria-label="查看 '+esc(p.code)+' 详情">'+art(p)+'</div><div class="card-info"><div class="between"><b class="mono code">'+esc(p.code)+'</b><span class="price">'+money(p.price)+'<small> / 个</small></span></div><h3>'+esc(p.name)+'</h3><div class="card-meta">'+p.pack+' 个 / 件 · '+p.min+' 件起订</div><div class="card-end"><div><small>'+esc(p.factory)+'</small><br><small class="mono">'+esc(p.factoryCode)+'</small></div><button data-action="detail" data-id="'+p.id+'">商品详情</button></div></div></article>').join('')+'</div>'}
function render(){if(!appReady)return;document.body.className='theme-a';$('#app').innerHTML=review()+'<div class="app">'+side()+'<main class="workspace">'+(activePage==='photo'?photoPage():title()+stats()+table())+'</main>'+(activePage==='products'?selectedbar():'')+'</div>';const all=$('#selectAll');if(all){let rows=result(),count=rows.filter(p=>selected.has(p.id)).length;all.indeterminate=count>0&&count<rows.length}persistDraft()}
function openDialog(title,sub,content,foot='',small=false){lastFocus=document.activeElement;const d=$('#dialog');d.className='dialog'+(small?' small':'');d.innerHTML='<div class="dialog-head"><div><h2 id="dialogTitle">'+title+'</h2><small>'+sub+'</small></div><button data-action="close" aria-label="关闭弹窗">×</button></div><div class="dialog-body">'+content+'</div>'+(foot?'<div class="dialog-foot">'+foot+'</div>':'');if(!d.open)d.showModal()}
function closeDialog(){if(updateTimer){clearInterval(updateTimer);updateTimer=null}$('#dialog').close();if(lastFocus?.isConnected)lastFocus.focus()}
function detail(id){const p=products.find(x=>x.id===id);openDialog('商品资料','编码映射、规格与厂家信息','<div class="detail-top"><div class="detail-art" style="background:'+(p.color||'#f3f6fa')+'">'+art(p)+'</div><div><span class="tag">'+esc(p.cat)+'</span><h2>'+esc(p.name)+'</h2><small>出厂价 / 个</small><div style="font-size:27px;margin-top:6px">'+money(p.price)+'</div></div></div><div class="mapping"><div><small>对客销售编码</small><div class="mono code">'+esc(p.code)+'</div></div>'+icon('arrow')+'<div><small>内部厂家编码</small><div class="mono">'+esc(p.factoryCode)+'</div></div><span class="tag" style="margin-left:auto">内部采购资料</span></div><div class="section-label">商品规格与包装</div><div class="fields">'+[['产品尺寸',p.size],['电池容量',p.battery],['充电头 / 接口',p.charger],['装箱数',p.pack+' 个 / 件'],['中包数',p.inner+' 个 / 中包'],['单件体积',p.volume+' m³'],['厂家名称',p.factory],['厂家地区',p.area],['起订件数',p.min+' 件']].map(x=>'<div class="field"><small>'+x[0]+'</small><b>'+esc(x[1])+'</b></div>').join('')+'</div><p class="prototype-note">件数、总数量在开单时填写与计算；当前按 1 件＝1 箱展示。</p>','<button data-action="edit" data-id="'+id+'">编辑资料</button><button class="primary" data-action="detailPick" data-id="'+id+'">'+(selected.has(id)?'从待开单移除':'加入待开单')+'</button>')}
function qty(p){return quantities[p.id]??p.min}
function total(){return picked().reduce((a,p)=>{let q=qty(p);a.cases+=q;a.units+=q*p.pack;a.amount+=q*p.pack*p.price;a.volume+=q*p.volume;return a},{cases:0,units:0,amount:0,volume:0})}
function order(){if(!selected.size)return toast('请先选择需要开单的商品');mode='single';for(const p of picked())if(!Number.isInteger(quantities[p.id])||quantities[p.id]<p.min)quantities[p.id]=p.min;openDialog('生成厂家报货单','第 2 步 · 填写件数，确认导出方式','<div class="notice" style="margin:0 0 18px">当前按 1 件＝1 箱；总数量＝件数 × 装箱数。金额按出厂单价计算。</div><div class="table-scroll"><table class="order-table"><thead><tr><th>商品 / 销售编码</th><th>厂家 / 厂家编码</th><th>装箱数</th><th>订货件数</th><th>总数量</th><th>金额</th></tr></thead><tbody>'+picked().map(p=>'<tr><td>'+esc(p.name)+'<br><small class="mono">'+esc(p.code)+'</small></td><td>'+esc(p.factory)+'<br><small class="mono">'+esc(p.factoryCode)+'</small></td><td>'+p.pack+' 个</td><td><input type="number" min="'+p.min+'" step="1" data-qty="'+p.id+'" aria-label="'+esc(p.code)+' 订货件数" value="'+qty(p)+'"><br><small id="qtyError'+p.id+'">'+p.min+' 件起订</small></td><td id="units'+p.id+'"></td><td id="amount'+p.id+'" class="price"></td></tr>').join('')+'</tbody></table></div><div class="order-settings"><div class="section-label">跨厂家导出方式</div><div class="radio-cards"><label class="radio-card"><input type="radio" name="exportMode" value="single" checked><div><b>生成一个 Excel</b><small>按厂家分工作表，方便自己统一核对。</small></div></label><label class="radio-card"><input type="radio" name="exportMode" value="multiple"><div><b>每个厂家一个 Excel</b><small>打包成 ZIP 下载，解压后分别发给厂家。</small></div></label></div><p id="exportHint" class="prototype-note" style="margin-top:10px"></p></div><div class="totals" id="orderTotals"></div>','<small>下载生成的报货单，不会自动发送给厂家。</small><button id="exportButton" class="primary" data-action="export">'+icon('file')+' 生成并下载</button>');refreshOrder()}
function refreshOrder(){let valid=true;for(const p of picked()){let q=qty(p),ok=Number.isInteger(q)&&q>=p.min&&q<=1000000;valid&&=ok;$('#qtyError'+p.id).className=ok?'':'bad';$('#qtyError'+p.id).textContent=ok?p.min+' 件起订':'请输入 ≥'+p.min+' 的整数（≤100万）';$('#units'+p.id).textContent=ok?q*p.pack+' 个':'—';$('#amount'+p.id).textContent=ok?money(q*p.pack*p.price):'—'}let t=total();$('#orderTotals').innerHTML=[['商品款数',selected.size,'款'],['订货件数',valid?t.cases:'—','件'],['商品总数量',valid?t.units:'—','个'],['总体积',valid?t.volume.toFixed(3):'—','m³'],['采购金额',valid?money(t.amount):'—','']].map(x=>'<div><small>'+x[0]+'</small><strong>'+x[1]+'<span>'+x[2]+'</span></strong></div>').join('');$('#exportButton').disabled=!valid;let count=new Set(picked().map(p=>p.factory)).size;$('#exportHint').textContent=mode==='single'?'将生成 1 个文件，包含 '+count+' 张厂家工作表。合并文件包含全部厂家的采购信息，转发前请注意选择。':'将生成 '+count+' 个 Excel 文件，以 1 个 ZIP 压缩包下载。'}
function suppliers(){openDialog('合作厂家','选择厂家后查看对应商品','<div class="stack">'+[...new Set(products.map(p=>p.factory))].map(f=>{let ps=products.filter(p=>p.factory===f);return '<div class="panel" style="padding:18px"><div class="between"><div><h3>'+esc(f)+'</h3><small>'+esc(ps[0].area)+' · '+ps.length+' 款商品</small></div><button data-action="filterFactory" data-factory="'+esc(f)+'">查看商品</button></div></div>'}).join('')+'</div>')}

function countInfo(){openDialog('“本次待开单”怎么统计？','统计当前这一次准备报货的商品清单。','<div class="count-example"><small>例如勾选 A-13 和 B-07</small><h2>2 款商品 · 2 家厂家</h2><p>即使每款订了多件，这里仍然计为 2 款。</p></div><div class="count-rules"><p><b>加入：</b>勾选或从商品详情加入，同一商品只计 1 款。</p><p><b>保留：</b>切换搜索、厂家筛选、列表 / 大图，已选商品都保留。</p><p><b>减少：</b>取消勾选或从清单移除；点击“清空”归零。</p><p><b>完成：</b>下载报货单后点击“完成本次并清空”，开始下一单。</p></div><p class="prototype-note">不统计历史订单；件数、总数量在开单弹窗中单独计算。未完成清单会保存在本机，关闭重开后可继续。</p>','<small>当前已选 '+selected.size+' 款商品</small><button class="primary" data-action="close">明白了</button>',true)}
function showPending(){openDialog('本次待开单清单','共 '+selected.size+' 款商品 · '+new Set(picked().map(p=>p.factory)).size+' 家厂家 · 包含当前筛选未展示的已选商品','<div class="stack">'+(picked().map(p=>'<div class="pending-item">'+thumb(p)+'<div class="grow"><b class="mono code">'+esc(p.code)+'</b><h3>'+esc(p.name)+'</h3><small>'+esc(p.factory)+'</small></div><button class="quiet danger" data-action="pendingRemove" data-id="'+p.id+'">移除</button></div>').join('')||'<div class="empty">清单为空，返回商品资料继续选货。</div>')+'</div>','<button data-action="close">继续选货</button><button class="primary" data-action="pendingOrder" '+(!selected.size?'disabled':'')+'>填写件数并开单</button>',true)}

let activePage='products',photoUrl='',photoName='',photoRotation=0,photoRows=[],photoRowCounter=0;
async function loadOrderPhoto(file){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type))return toast('请选择 JPG、PNG 或 WEBP 图片');if(file.size>15*1024*1024)return toast('图片超过 15 MB，请压缩后再上传');const next=URL.createObjectURL(file);try{await new Promise((resolve,reject)=>{const im=new Image();im.onload=resolve;im.onerror=reject;im.src=next});if(photoUrl.startsWith('blob:'))URL.revokeObjectURL(photoUrl);photoFile=file;photoUrl=next;photoName=file.name;photoRotation=0;photoRows=[];render();toast('图片已载入，可继续体验识别确认流程')}catch{URL.revokeObjectURL(next);toast('图片无法读取，请换一张清晰完整的图片')}}
function photoResult(r){const p=products.find(p=>p.id===r.id);if(!p)return {ok:false,text:'未匹配商品，请手动选择。'};if(!r.unit)return {ok:false,text:'数量单位不明，请对照原图确认。'};if(!Number.isInteger(r.quantity)||r.quantity<=0||r.quantity>1000000)return {ok:false,text:'数量须为 1～100 万的整数。'};const cases=r.unit==='个'?r.quantity/p.pack:r.quantity;if(!Number.isInteger(cases))return {ok:false,text:r.quantity+' 个不足整件（每件 '+p.pack+' 个），请核对数量。'};return {ok:true,p,cases,units:cases*p.pack,text:cases+' 件 × '+p.pack+' 个/件 = '+cases*p.pack+' 个'} }
function photoTotals(){let groups=new Map(),problems=0,unreviewed=0;for(const r of photoRows){const calc=photoResult(r);if(!calc.ok){problems++;continue}if(!r.reviewed)unreviewed++;groups.set(r.id,(groups.get(r.id)||0)+calc.cases)}let minimums=[...groups].filter(([id,q])=>q<products.find(p=>p.id===id).min||q>1000000);return {groups,problems,unreviewed,minimums,valid:photoRows.length>0&&!problems&&!unreviewed&&!minimums.length}}
function photoRowMarkup(r,index){return '<article class="ocr-row" data-photo-row="'+r.key+'"><div class="between"><b class="ocr-row-title">第 '+(index+1)+' 行</b><button class="quiet danger" data-action="photoRowRemove" data-key="'+r.key+'">移除</button></div><div class="ocr-source"><span>识别原文</span><b>'+esc(r.raw||'手动补充')+'</b></div><label class="ocr-label">对应商品<select data-photo-field="id" data-key="'+r.key+'" aria-label="第 '+(index+1)+' 行对应商品"><option value="0">未匹配 · 请选择商品</option>'+products.map(p=>'<option value="'+p.id+'" '+(r.id===p.id?'selected':'')+'>'+esc(p.code+' · '+p.name+' / '+p.factory)+'</option>').join('')+'</select></label><div class="ocr-inputs"><label class="ocr-label">数量<input type="number" min="1" step="1" max="1000000" data-photo-field="quantity" data-key="'+r.key+'" value="'+r.quantity+'" aria-label="第 '+(index+1)+' 行数量"></label><label class="ocr-label">单位<select data-photo-field="unit" data-key="'+r.key+'" aria-label="第 '+(index+1)+' 行单位">'+[['','待确认'],['件','件 / 箱'],['个','个']].map(([v,t])=>'<option value="'+v+'" '+(r.unit===v?'selected':'')+'>'+t+'</option>').join('')+'</select></label><div class="ocr-converted" id="photoCalc'+r.key+'"></div></div><div class="between ocr-checkline"><span class="tag" id="photoTag'+r.key+'"></span><label><input type="checkbox" data-photo-field="reviewed" data-key="'+r.key+'" '+(r.reviewed?'checked':'')+'> 已核对商品、数量和单位</label></div></article>'}
function showPhotoConfirmation(){openDialog('报单确认','图片开单 · 先核对商品和数量，再选择按厂家导出。','<div class="ocr-demo-banner">离线识别结果需要人工核对，可能漏行或错字。请对照原图检查并补充，不能直接作为下单依据。</div><details class="raw-ocr"><summary>查看全部识别原文</summary><pre>'+esc(ocrLines.map(l=>l.text).join('\n')||'无识别原文，可手动录入')+'</pre></details><div class="ocr-layout"><aside class="ocr-original"><div class="between"><b>订单原图</b><div class="flex"><button class="quiet" data-action="photoZoom">放大</button><button class="quiet" data-action="photoConfirmRotate" aria-label="旋转订单原图">'+icon('refresh')+'</button></div></div><div class="ocr-image"><img src="'+esc(photoUrl)+'" alt="供逐行核对的订单原图" style="transform:rotate('+photoRotation+'deg)"></div><small>'+esc(photoName)+'</small><p>对照原图逐行核对。无法确定的内容，修正或移除后再继续。</p></aside><section class="ocr-results"><div class="between ocr-results-head"><h3>商品与数量</h3><span id="photoIssueSummary"></span></div>'+photoRows.map(photoRowMarkup).join('')+(!photoRows.length?'<div class="empty">已移除全部行，可手动补充商品。</div>':'')+'<button class="wide photo-add-row" data-action="photoRowAdd">＋ 补充一行商品</button><div id="photoMinimums"></div><div class="ocr-overwrite">'+(selected.size?'当前待开单中已有 '+selected.size+' 款商品。确认后将用本张图片的清单替换；取消不会改变原清单。':'确认后将加入本次待开单；同一商品出现多行时，件数合并统计。')+'</div></section></div>','<button data-action="close">返回图片</button><small id="photoConfirmSummary"></small><button class="primary" id="photoApplyButton" data-action="photoApply" disabled>'+(selected.size?'替换清单并继续':'确认商品与数量')+' '+icon('arrow')+'</button>');$('#dialog').classList.add('photo-dialog');updatePhotoSummary()}
function updatePhotoSummary(){const totals=photoTotals();for(const r of photoRows){const calc=photoResult(r),bad=calc.ok&&totals.minimums.some(([id])=>id===r.id),tag=$('#photoTag'+r.key),line=$('#photoCalc'+r.key);line.textContent=calc.text;line.classList.toggle('invalid',!calc.ok);tag.textContent=!calc.ok?'待修正':bad?'起订量不足':r.reviewed?'已核对':'待人工核对';tag.classList.toggle('needs-review',!calc.ok||!r.reviewed||bad);const box=$('[data-photo-field="reviewed"][data-key="'+r.key+'"]');box.disabled=!calc.ok;box.checked=r.reviewed&&calc.ok}$('#photoIssueSummary').textContent=totals.problems+totals.unreviewed+totals.minimums.length?'请完成核对':'全部核对完成';$('#photoMinimums').innerHTML=totals.minimums.map(([id,q])=>{let p=products.find(p=>p.id===id);return '<div class="notice" style="margin:10px 0">'+esc(p.code)+' 合计 '+q+' 件；'+(q>1000000?'超出 100 万件上限。':'最低 '+p.min+' 件起订，请核对数量。')+'</div>'}).join('');let cases=[...totals.groups.values()].reduce((a,b)=>a+b,0);$('#photoConfirmSummary').textContent=totals.problems?'还有 '+totals.problems+' 行需要修正商品或数量':totals.unreviewed?'还有 '+totals.unreviewed+' 行未勾选核对':totals.minimums.length?'请修正起订件数或件数上限':'共 '+totals.groups.size+' 款商品 · '+cases+' 件';$('#photoApplyButton').disabled=!totals.valid}
function applyPhotoOrder(){const t=photoTotals();if(!t.valid)return toast('请先修正问题并逐行确认');selected=new Set(t.groups.keys());quantities=Object.fromEntries(t.groups);closeDialog();render();order();$('#dialogTitle').textContent='报单确认 · 数量与导出';$('#dialog .dialog-head small').textContent='来自图片开单 · 已人工核对商品与数量，可再次调整后导出。'}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;if(a==='photo'){activePage='photo';render()}else if(a==='photoChoose')$('#orderPhotoInput').click();else if(a==='photoRemove'){photoFile=null;if(photoUrl.startsWith('blob:'))URL.revokeObjectURL(photoUrl);photoUrl='';photoName='';photoRows=[];render()}else if(a==='photoRotate'){photoRotation=(photoRotation+90)%360;render()}else if(a==='photoRecognize')beginPhotoDemo();else if(a==='photoConfirmRotate'){photoRotation=(photoRotation+90)%360;$('#dialog .ocr-image img').style.transform='rotate('+photoRotation+'deg)'}else if(a==='photoZoom'){openDialog('查看订单原图','可对照照片核对手写内容。','<div class="photo-zoom"><img src="'+esc(photoUrl)+'" alt="订单原图"></div>','<small>原图按原始方向展示</small><button class="primary" data-action="photoReturnConfirm">返回核对</button>');$('#dialog').classList.add('photo-dialog')}else if(a==='photoReturnConfirm')showPhotoConfirmation();else if(a==='photoRowRemove'){photoRows=photoRows.filter(r=>r.key!==Number(b.dataset.key));showPhotoConfirmation()}else if(a==='photoRowAdd'){photoRows.push({key:++photoRowCounter,raw:'手动补充',id:0,quantity:1,unit:'',reviewed:false});showPhotoConfirmation()}else if(a==='photoApply')applyPhotoOrder()});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='orderPhotoInput')loadOrderPhoto(t.files[0]);if(t.dataset.photoField){const r=photoRows.find(r=>r.key===Number(t.dataset.key));if(!r)return;if(t.dataset.photoField==='reviewed')r.reviewed=t.checked;else if(t.dataset.photoField==='id'){r.id=Number(t.value);r.reviewed=false}else if(t.dataset.photoField==='unit'){r.unit=t.value;r.reviewed=false}updatePhotoSummary()}});
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.photoField==='quantity'){const r=photoRows.find(r=>r.key===Number(t.dataset.key));r.quantity=t.value===''?0:Number(t.value);r.reviewed=false;updatePhotoSummary()}});
document.addEventListener('dragover',e=>{if(activePage==='photo'&&!$('#dialog').open){e.preventDefault();e.target.closest('[data-dropzone]')?.classList.add('dragging')}});
document.addEventListener('dragleave',e=>e.target.closest?.('[data-dropzone]')?.classList.remove('dragging'));
document.addEventListener('drop',e=>{if(activePage==='photo'&&!$('#dialog').open){e.preventDefault();loadOrderPhoto(e.dataTransfer.files[0])}});
document.addEventListener('paste',e=>{if(activePage==='photo'&&!$('#dialog').open){const file=[...e.clipboardData.items].find(x=>x.kind==='file'&&x.type.startsWith('image/'))?.getAsFile();if(file){e.preventDefault();loadOrderPhoto(file)}}});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.photo-drop')){e.preventDefault();$('#orderPhotoInput').click()}});

document.addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(!b||b.disabled)return;let a=b.dataset.action,id=Number(b.dataset.id);if(a==='viewMode'){viewMode=b.dataset.view;render()}else if(a==='pending')showPending();else if(a==='countInfo')countInfo();else if(a==='pendingRemove'){selected.delete(id);render();showPending()}else if(a==='pendingOrder'){closeDialog();order()}else if(a==='finishOrder'){selected.clear();quantities={};closeDialog();render();toast('本次开单已完成，待开单清单已清空')}else if(a==='close')closeDialog();else if(a==='all'||a==='reset'){activePage='products';query='';factory='';category='';render()}else if(a==='search'){query=($('#search')||$('#batchSearch')).value;render()}else if(a==='example'){query=products.slice(0,3).map(p=>p.code).join(', ');factory='';category='';render()}else if(a==='cat'){category=b.dataset.cat;render()}else if(a==='clear'){selected.clear();render()}else if(a==='toggle'){selected.has(id)?selected.delete(id):selected.add(id);render()}else if(a==='addAll'){result().forEach(p=>selected.add(p.id));render()}else if(a==='detail')detail(id);else if(a==='detailPick'){selected.has(id)?selected.delete(id):selected.add(id);closeDialog();render()}else if(a==='new'||a==='edit')newForm(a==='edit'?id:0);else if(a==='order')order();else if(a==='export')exportOrder();else if(a==='import')showImport(1);else if(a==='importNext')showImport(2);else if(a==='importValidate')validateImport();else if(a==='importCommit')importCommit();else if(a==='update')showUpdate();else if(a==='backup')backup();else if(a==='suppliers')suppliers();else if(a==='filterFactory'){activePage='products';factory=b.dataset.factory;query='';category='';closeDialog();render()}});
document.addEventListener('change',e=>{let t=e.target;if(t.dataset.select){let id=Number(t.dataset.select);t.checked?selected.add(id):selected.delete(id);render()}else if(t.id==='selectAll'){result().forEach(p=>t.checked?selected.add(p.id):selected.delete(p.id));render()}else if(t.id==='factory'){factory=t.value;render()}else if(t.name==='exportMode'){mode=t.value;refreshOrder()}});
document.addEventListener('input',e=>{let t=e.target;if(t.dataset.qty){quantities[t.dataset.qty]=t.value===''?NaN:Number(t.value);refreshOrder()}if(t.id==='search'||t.id==='batchSearch')query=t.value});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='search'){query=e.target.value;render()}else if((e.key==='Enter'||e.key===' ')&&e.target.classList.contains('card-visual')){e.preventDefault();detail(Number(e.target.dataset.id))}});
document.addEventListener('submit',e=>{if(e.target.id==='productForm'){e.preventDefault();saveProduct(e.target)}});$('#dialog').addEventListener('cancel',()=>{if(updateTimer){clearInterval(updateTimer);updateTimer=null}});
let appReady=false,appState={},draftLastSaved='',draftSending=null,draftError=false,productImage='',photoFile=null,ocrLines=[],importSession=null,importPreview=null;
async function api(path,options={}){const headers={'X-Counter-Request':'1',...(options.headers||{})};if(options.body&&!(options.body instanceof FormData)){headers['Content-Type']='application/json';options.body=JSON.stringify(options.body)}const r=await fetch(path,{...options,headers});if(!r.ok){let err;try{err=await r.json()}catch{}throw Error(typeof err?.detail==='string'?err.detail:'操作失败（'+r.status+'），请重试')}return r.json()}
async function bootstrap(){try{appState=await api('/api/state');products=appState.products;version=appState.version;selected=new Set(appState.draft.selected||[]);quantities=appState.draft.quantities||{};draftLastSaved=JSON.stringify(draftData());appReady=true;render()}catch(e){$('#app').innerHTML='<div class="connection-error"><h2>无法连接本地服务</h2><p>'+esc(e.message)+'</p><p>请重新双击“档口开单系统.exe”打开。</p><button data-action="reload">重新连接</button></div>'}}
function draftData(){return {selected:[...selected],quantities:Object.fromEntries([...selected].map(id=>[String(id),Number.isFinite(quantities[id])?quantities[id]:products.find(p=>p.id===id)?.min||1]))}}
async function persistDraft(){if(!appReady)return;if(draftSending){await draftSending;return draftError?undefined:persistDraft()}const snapshot=JSON.stringify(draftData());if(snapshot===draftLastSaved)return;draftSending=(async()=>{try{await api('/api/draft',{method:'PUT',body:JSON.parse(snapshot)});draftLastSaved=snapshot;draftError=false}catch(e){draftError=true;toast('清单尚未保存：'+e.message)}finally{const status=$('#saveState');if(status){status.textContent=draftError?'清单未保存，请重试':'数据保存在本机';status.style.color=draftError?'#c45e42':''}}})();await draftSending;draftSending=null;if(!draftError&&JSON.stringify(draftData())!==draftLastSaved)return persistDraft()}
async function refreshProducts(){const s=await api('/api/state');products=s.products;appState=s;render()}
function review(){return ''}
function productImageMarkup(){return productImage?'<img src="/api/images/'+productImage+'" alt="产品图片"><button type="button" class="image-remove" data-action="removeProductImage" aria-label="删除产品图片">×</button>':'<div class="product-image-empty"><strong>拖拽图片到这里</strong><small>或点击选择图片</small></div>'}
function renderProductImagePreview(){const preview=$('#productImagePreview');if(preview)preview.innerHTML=productImageMarkup()}
async function uploadProductImage(file){if(!file||!file.type.startsWith('image/'))return toast('请选择 JPG、PNG 或 WEBP 图片');const button=$('[form="productForm"]');if(button)button.disabled=true;try{const fd=new FormData();fd.append('file',file);productImage=(await api('/api/images',{method:'POST',body:fd})).image;renderProductImagePreview()}catch(err){toast(err.message)}finally{if(button)button.disabled=false}}
function newForm(id){const p=products.find(p=>p.id===id)||{code:'',factoryCode:'',name:'',factory:'',area:'',size:'',battery:'',charger:'',pack:'',inner:'',volume:'',price:'',min:'',cat:'日用百货',notes:'',image:''};productImage=p.image||'';const fields=[['code','销售编码',true],['factoryCode','厂家编码',true],['name','产品名称',true],['factory','厂家名称',true],['area','厂家地区',false],['size','尺寸',false],['battery','电池容量',false],['charger','充电头 / 接口',false],['pack','装箱数（个 / 件）',false],['inner','中包数（个 / 中包）',false],['volume','单件体积（m³）',false],['price','出厂价（元 / 个）',false],['min','起订件数',false]];openDialog(id?'编辑商品资料':'新增商品','保存后写入本机数据库，关闭软件后仍会保留。','<form id="productForm" data-id="'+(id||'')+'"><div class="product-image-editor"><div id="productImagePreview" class="product-image-dropzone" data-product-image-dropzone tabindex="0" role="button" aria-label="拖拽或点击上传产品图片">'+productImageMarkup()+'</div><input type="file" id="productImageInput" accept="image/jpeg,image/png,image/webp" hidden><p class="prototype-note">拖拽图片到此处，或点击选择 · JPG / PNG / WEBP，最大 15 MB</p></div><div class="form-grid">'+fields.map(([k,l,required])=>'<label><span class="form-label">'+l+(required?' <em class="required-mark">*</em>':'')+'</span><input name="'+k+'" value="'+esc(p[k]??'')+'" '+(['pack','inner','min'].includes(k)?'type="number" min="1" max="1000000" step="1"':k==='price'?'type="number" min="0" step="0.01"':k==='volume'?'type="number" min="0" step="0.000001"':'maxlength="300"')+(required?' required':'')+'></label>').join('')+'<label><span class="form-label">商品分类</span><input name="cat" value="'+esc(p.cat||'')+'" maxlength="300"></label><label style="grid-column:1/-1"><span class="form-label">备注</span><textarea name="notes" maxlength="300">'+esc(p.notes||'')+'</textarea></label></div></form>','<small>销售编码唯一；厂家编码在同一厂家内唯一。</small><button class="primary" type="submit" form="productForm">保存商品</button>')}
async function saveProduct(form){if(!form.reportValidity())return;const button=$('[form="productForm"]');button.disabled=true;try{let data=Object.fromEntries(new FormData(form)),id=Number(form.dataset.id);data.image=productImage;for(const [k,defaultValue] of [['pack',1],['inner',1],['volume',0],['price',0],['min',1]])data[k]=data[k]===''?defaultValue:Number(data[k]);await api(id?'/api/products/'+id:'/api/products',{method:id?'PUT':'POST',body:data});closeDialog();await refreshProducts();toast('商品资料已保存到本机')}catch(e){toast(e.message)}finally{button.disabled=false}}
async function exportOrder(){const button=$('#exportButton');button.disabled=true;try{const result=await api('/api/orders',{method:'POST',body:{items:picked().map(p=>({id:p.id,quantity:qty(p)})),mode}});const a=document.createElement('a');a.href=result.url;a.download=result.filename;a.click();toast('报货单已生成，可在“导出记录”中再次下载');if(!$('#finishOrderButton')){button.insertAdjacentHTML('beforebegin','<button id="finishOrderButton" data-action="finishOrder">完成本次并清空</button>');$('#dialog .dialog-foot small').textContent='确认下载完成后，可清空本次清单。关闭弹窗保留清单。'}button.textContent='再次生成并下载'}catch(e){toast(e.message)}finally{button.disabled=false}}
function showImport(step=1){if(step===1){importSession=null;importPreview=null;openDialog('Excel 导入商品','上传厂家表格，映射字段、预览校验后再写入数据库。','<div class="upload-box">'+icon('upload')+'<h3>选择厂家商品资料表</h3><p>支持 .xlsx / .xls，最大 30 MB，每批最多 10000 行。</p><label class="upload-label">选择 Excel 文件<input id="bookInput" type="file" accept=".xlsx,.xls" hidden></label></div><div class="between" style="margin-top:18px"><small>没有现成表格？可使用系统导入模板。</small><a href="/api/import-template" class="help-link">下载导入模板</a></div><p class="prototype-note">原表不会被修改。复杂图片公式和多图行需要导入后核对；旧版 .xls 图片请手动补充。</p>','<small id="importStatus">只在本机处理文件</small><button data-action="close">取消</button>');return}if(!importPreview)return;drawImportMapping()}
async function uploadBook(file){if(!file)return;$('#importStatus').textContent='正在读取表格，请稍候…';try{const fd=new FormData();fd.append('file',file);importSession=await api('/api/import/upload',{method:'POST',body:fd});importSession.config={sheet:importSession.sheets[0],header:1,prefix:'',start:1,factory:''};importPreview=await api('/api/import/preview',{method:'POST',body:{batch:importSession.batch,...importSession.config}});importSession.config.mapping=importPreview.mapping;drawImportMapping()}catch(e){if($('#importStatus'))$('#importStatus').textContent=e.message;toast(e.message)}}
function importConfig(){const config={sheet:$('#importSheet').value,header:Number($('#importHeader').value),factory:$('#importFactory').value.trim(),prefix:$('#importPrefix').value.trim(),start:Number($('#importStart').value),mapping:{}};document.querySelectorAll('[data-import-field]').forEach(e=>{if(e.value!=='')config.mapping[e.dataset.importField]=Number(e.value)});return config}
function drawImportMapping(){const c=importSession.config;openDialog('对应表格字段','文件：'+esc(importSession.filename)+' · 字段对应后点击校验预览。','<div class="form-grid"><label>工作表<select id="importSheet">'+importSession.sheets.map(s=>'<option '+(s===c.sheet?'selected':'')+'>'+esc(s)+'</option>').join('')+'</select></label><label>表头行<input id="importHeader" type="number" min="1" max="50" value="'+c.header+'"></label></div><button data-action="importReloadHeaders" style="margin:14px 0">重新读取表头</button><div class="import-mappings">'+Object.entries(importSession.fields).map(([key,label])=>'<label>'+esc(label)+'<select data-import-field="'+key+'"><option value="">不导入 / 使用默认值</option>'+importPreview.headers.map((h,i)=>'<option value="'+i+'" '+(c.mapping[key]===i?'selected':'')+'>'+(i+1)+' · '+esc(h||'空列名')+'</option>').join('')+'</select></label>').join('')+'</div><div class="form-grid" style="margin-top:20px"><label>统一厂家名称（原表没有时填写）<input id="importFactory" value="'+esc(c.factory)+'"></label><label>销售编码前缀（原表没有时填写）<input id="importPrefix" value="'+esc(c.prefix)+'" placeholder="例如 A"></label><label>编码起始序号<input id="importStart" type="number" min="1" step="1" value="'+c.start+'"></label></div><p class="prototype-note">未填默认值：起订件数 1、中包数 1、单件体积 0；提交前请核对。价格和装箱数没有默认值，缺失行会被标记。</p>','<button data-action="import">重新选择文件</button><button class="primary" data-action="importValidate">校验并预览</button>')}
async function reloadImportHeaders(){const button=$('[data-action="importReloadHeaders"]');button.disabled=true;try{const c=importConfig();delete c.mapping;importPreview=await api('/api/import/preview',{method:'POST',body:{batch:importSession.batch,...c}});importSession.config={...c,mapping:importPreview.mapping};drawImportMapping()}catch(e){toast(e.message)}finally{button.disabled=false}}
async function validateImport(){const button=$('[data-action="importValidate"]');button.disabled=true;try{importSession.config=importConfig();importPreview=await api('/api/import/preview',{method:'POST',body:{batch:importSession.batch,...importSession.config}});openDialog('核对后导入','仅提交校验通过的行；错误和重复行会跳过，不覆盖已有资料。','<div class="import-result"><b>共 '+importPreview.total+' 行 · 可导入 '+importPreview.valid+' 行 · 问题行 '+(importPreview.total-importPreview.valid)+' 行</b></div>'+importPreview.warnings.map(w=>'<div class="notice" style="margin:10px 0">'+esc(w)+'</div>').join('')+'<div class="table-scroll import-result-table"><table><thead><tr><th>原表行</th><th>销售编码</th><th>商品名称</th><th>厂家</th><th>装箱数</th><th>单价</th><th>校验结果</th></tr></thead><tbody>'+importPreview.rows.slice(0,100).map(r=>'<tr><td>'+r.row+'</td><td>'+esc(r.data.code)+'</td><td>'+esc(r.data.name)+'</td><td>'+esc(r.data.factory)+'</td><td>'+esc(r.data.pack)+'</td><td>'+esc(r.data.price)+'</td><td style="color:'+(r.error?'#c56745':'#338a69')+'">'+esc(r.error||'可导入')+'</td></tr>').join('')+'</tbody></table></div><p class="prototype-note">仅展示前 100 行，提交处理全部 '+importPreview.total+' 行。</p>','<button data-action="importNext">返回修改</button><button data-action="importErrors">下载问题行 CSV</button><button class="primary" data-action="importCommit" '+(!importPreview.valid?'disabled':'')+'>导入有效的 '+importPreview.valid+' 行</button>')}catch(e){toast(e.message)}finally{button.disabled=false}}
async function importCommit(){const button=$('[data-action="importCommit"]');button.disabled=true;try{const r=await api('/api/import/commit',{method:'POST',body:{batch:importSession.batch,previewId:importPreview.previewId}});closeDialog();query='';factory='';category='';await refreshProducts();toast('成功导入 '+r.count+' 款商品')}catch(e){toast(e.message);button.disabled=false}}
function importErrors(){const rows=importPreview.rows.filter(r=>r.error);if(!rows.length)return toast('没有问题行');const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const fields=Object.keys(importSession.fields);const data=[['原表行','问题',...Object.values(importSession.fields)],...rows.map(r=>[r.row,r.error,...fields.map(k=>r.data[k])])].map(r=>r.map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='导入问题行.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
async function backup(){try{const files=await api('/api/backups');openDialog('数据与备份','数据目录：'+esc(appState.dataDir),'<div class="between"><div><h3>备份数据库、图片和未完成清单</h3><p class="prototype-note">每天首次启动自动备份。可下载备份到其他设备，防止本机硬盘损坏。</p></div><button class="primary" data-action="backupCreate">立即备份</button></div><div class="table-scroll" style="margin-top:20px"><table><thead><tr><th>备份文件</th><th>大小</th><th>操作</th></tr></thead><tbody>'+files.map(f=>'<tr><td>'+esc(f.name)+'</td><td>'+(f.size/1024/1024).toFixed(2)+' MB</td><td><a href="/api/backups/'+encodeURIComponent(f.name)+'">下载</a>　<button data-action="backupRestore" data-name="'+esc(f.name)+'">恢复</button></td></tr>').join('')+'</tbody></table></div>','<small>恢复前会先自动备份当前资料。</small><button data-action="close">关闭</button>')}catch(e){toast(e.message)}}
async function createBackup(){const b=$('[data-action="backupCreate"]');b.disabled=true;try{await api('/api/backups',{method:'POST'});await backup();toast('备份已完成')}catch(e){toast(e.message);b.disabled=false}}
function restorePrompt(name){openDialog('恢复备份','将恢复数据库及对应图片，当前资料会先另存一份安全备份。','<p>备份：'+esc(name)+'</p><label class="stack" style="margin-top:18px">输入“恢复备份”确认<input id="restoreConfirm" autocomplete="off"></label>','<button data-action="backup">返回</button><button class="primary" data-action="backupRestoreConfirm" data-name="'+esc(name)+'">恢复备份</button>',true)}
async function restoreBackup(name){try{await api('/api/backups/restore',{method:'POST',body:{name,confirmation:$('#restoreConfirm').value}});appReady=false;closeDialog();await bootstrap();toast('资料已从备份恢复')}catch(e){toast(e.message)}}
async function history(){try{const rows=await api('/api/orders');openDialog('导出记录','保留最近 100 次生成记录；商品修改不会改变已生成报货单。','<div class="table-scroll"><table><thead><tr><th>开单时间</th><th>商品款数</th><th>件数</th><th>文件</th></tr></thead><tbody>'+rows.map(o=>'<tr><td>'+esc(o.createdAt.replace('T',' '))+'</td><td>'+o.items.length+'</td><td>'+o.items.reduce((n,p)=>n+p.quantity,0)+'</td><td><a href="/api/exports/'+encodeURIComponent(o.file)+'">下载报货单</a></td></tr>').join('')+'</tbody></table></div>'+(!rows.length?'<div class="empty">还没有生成过报货单。</div>':''))}catch(e){toast(e.message)}}
function showUpdate(){openDialog('软件版本与维护','当前版本 '+version+' · 本地版','<div class="update-intro"><div class="update-mark">'+icon('refresh')+'</div><h2>尚未配置在线更新源</h2><p>本版本不会联网查询或安装更新。</p></div><div class="update-notes">新版本可由维护者提供完整程序包。先备份、退出旧程序，再解压新版并运行。业务数据位于独立目录，替换程序不删除商品资料。<br>自动更新需要后续配置发布地址及升级校验。</div>','<small>数据仍保存在本机</small><button class="primary" data-action="close">了解了</button>',true)}
function photoPage(){return '<div class="between page-title"><div><h1>图片开单</h1><p>识别在本机完成，不上传图片；手写内容请逐行核对。</p></div><span class="tag">'+(appState.ocrAvailable?'离线识别可用':'可手动录入')+'</span></div><div class="photo-steps"><div><span>1</span><b>上传订单图片</b><small>照片或聊天截图</small></div><i></i><div><span>2</span><b>核对识别结果</b><small>商品、数量、单位</small></div><i></i><div><span>3</span><b>确认并导出</b><small>按厂家生成报货单</small></div></div><section class="panel photo-main"><div class="between panel-head"><h3>订单图片</h3><small>JPG / PNG / WEBP · 单张不超过 15 MB</small></div><input type="file" id="orderPhotoInput" accept="image/jpeg,image/png,image/webp" hidden>'+(photoUrl?'<div class="photo-selected"><div class="between"><b>'+esc(photoName)+'</b><div class="flex"><button class="quiet" data-action="photoChoose">更换图片</button><button class="quiet" data-action="photoRemove">移除</button></div></div><div class="photo-preview" data-dropzone><img src="'+esc(photoUrl)+'" alt="订单原图" style="transform:rotate('+photoRotation+'deg)"></div><div class="between photo-tools"><small>建议先旋转到文字朝上，再开始识别。</small><button data-action="photoRotate">'+icon('refresh')+' 旋转 90°</button></div></div>':'<div class="photo-drop" data-dropzone tabindex="0" role="button" aria-label="选择或拖入订单图片" data-action="photoChoose"><div class="photo-upload-icon">'+icon('image')+'</div><h2>上传客户的订单图片</h2><p>拖入图片、点击选择文件，或直接粘贴截图</p><span class="primary-upload">'+icon('upload')+' 上传订单图片</span><small>拍正、拍清，保留商品编码和数量单位。</small></div>')+'<div class="photo-action"><div><b>先核对，再开单</b><p>潦草手写可能无法准确识别，可手动补充商品和数量。</p></div><div class="flex"><button data-action="photoManual" '+(!photoUrl?'disabled':'')+'>对照图片手动录入</button><button class="primary" data-action="photoRecognize" '+(!photoUrl||!appState.ocrAvailable?'disabled':'')+'>开始离线识别 '+icon('arrow')+'</button></div></div><div id="ocrStatus" class="photo-demo-note">仅识别你选择的这张图片，无付费调用。首次识别需要加载本机模型，可能稍慢。</div></section>'}
async function beginPhotoDemo(){if(!photoFile)return toast('请先上传订单图片');const button=$('[data-action="photoRecognize"]');button.disabled=true;$('#ocrStatus').textContent='正在本机识别，请稍候… 请勿关闭软件。';try{const fd=new FormData();fd.append('file',photoFile);const r=await api('/api/recognize?rotation='+photoRotation,{method:'POST',body:fd});ocrLines=r.lines;photoRows=r.rows.map(row=>({...row,key:++photoRowCounter}));if(!photoRows.length)photoRows=[{key:++photoRowCounter,raw:'未能可靠提取商品行，请对照原图手动补充。',id:0,quantity:0,unit:'',reviewed:false}];showPhotoConfirmation()}catch(e){toast('识别未完成：'+e.message);if($('#ocrStatus'))$('#ocrStatus').textContent='识别失败，可重试或对照图片手动录入。'}finally{button.disabled=false}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;if(a==='reload')bootstrap();else if(a==='history')history();else if(a==='importReloadHeaders')reloadImportHeaders();else if(a==='importErrors')importErrors();else if(a==='backupCreate')createBackup();else if(a==='backupRestore')restorePrompt(b.dataset.name);else if(a==='backupRestoreConfirm')restoreBackup(b.dataset.name);else if(a==='removeProductImage'){productImage='';renderProductImagePreview()}else if(a==='photoManual'){ocrLines=[];photoRows=[{key:++photoRowCounter,raw:'手动录入',id:0,quantity:1,unit:'',reviewed:false}];showPhotoConfirmation()}else if(a==='shutdown'){openDialog('退出系统','退出前会保存当前待开单清单。','<p>关闭浏览器标签页不会停止本地服务。点击下方按钮退出软件。</p>','<button data-action="close">取消</button><button class="primary" data-action="shutdownConfirm">保存并退出</button>',true)}else if(a==='shutdownConfirm'){persistDraft().then(async()=>{if(draftError)return;await api('/api/shutdown',{method:'POST'});closeDialog();appReady=false;$('#app').innerHTML='<div class="connection-error"><h2>系统已退出</h2><p>资料已保存在本机，可以关闭此页面。</p></div>'}).catch(e=>toast(e.message))}});
document.addEventListener('click',e=>{if(e.target.closest('[data-product-image-dropzone]')&&!e.target.closest('[data-action]'))$('#productImageInput')?.click()});
document.addEventListener('change',e=>{if(e.target.id==='bookInput')uploadBook(e.target.files[0]);if(e.target.id==='productImageInput')uploadProductImage(e.target.files[0])});
document.addEventListener('dragover',e=>{const zone=e.target.closest('[data-product-image-dropzone]');if(!zone)return;e.preventDefault();zone.classList.add('dragging')});
document.addEventListener('dragleave',e=>{const zone=e.target.closest('[data-product-image-dropzone]');if(zone&&!zone.contains(e.relatedTarget))zone.classList.remove('dragging')});
document.addEventListener('drop',e=>{const zone=e.target.closest('[data-product-image-dropzone]');if(!zone)return;e.preventDefault();zone.classList.remove('dragging');uploadProductImage(e.dataTransfer.files[0])});
document.addEventListener('input',e=>{if(e.target.dataset.qty)persistDraft()});
window.addEventListener('pagehide',()=>{if(appReady&&JSON.stringify(draftData())!==draftLastSaved)fetch('/api/draft',{method:'PUT',keepalive:true,headers:{'Content-Type':'application/json','X-Counter-Request':'1'},body:JSON.stringify(draftData())}).catch(()=>{})});
const legacyRender=render;
render=function(){legacyRender();document.querySelector('.batch-example')?.remove();const helper=document.querySelector('.library-helper');if(helper){const label=helper.querySelector('label');const target=document.querySelector('.panel-head .flex:last-child');if(label&&target)target.insertBefore(label,target.firstChild);helper.remove()}};

bootstrap();
